//soft ui components
import DashboardLayout from '../../../../examples/LayoutContainers/DashboardLayout';
import DashboardNavbar from '../../../../examples/Navbars/DashboardNavbar';
import SoftBox from '../../../../components/SoftBox';
import SoftSelect from '../../../../components/SoftSelect';
import SoftTypography from '../../../../components/SoftTypography';
import phone from '../../../../assets/images/ecommerce/phone.png';

//mui components
import { Button, Checkbox, InputLabel, Switch } from '@mui/material';

//react
import { useNavigate } from 'react-router-dom';
import { useState } from 'react';

//styles
import './loyalitypoints.css';

//icons
import CircleNotificationsOutlinedIcon from '@mui/icons-material/CircleNotificationsOutlined';
import DeleteOutlineOutlinedIcon from '@mui/icons-material/DeleteOutlineOutlined';
import SmsIcon from '@mui/icons-material/Sms';
import WhatsAppIcon from '@mui/icons-material/WhatsApp';
import bluestar from '../../../../assets/images/ecommerce/bluestars.png';

const label = { inputProps: { 'aria-label': 'Switch demo' } };

export const MultipleOrderAlert = () => {

  const navigate = useNavigate();

  const [checked, setChecked] = useState(false);
  const [checkedBox, setCheckedBox] = useState(false);
  const [isSwitch, setIsSwitch] = useState(false);
  const [addMore, setAddMore] = useState(false);
  const [mobileList, setMobileList] = useState([]);
  const [mobile, setMobile] = useState('');

  const [isEntering, setIsEntering] = useState(false);

  const switchHandler = (event) => {
    setChecked(event.target.checked);
  };

  const getCurrentMonthDays = () => {
    const currentDate = new Date();
    const currentMonth = currentDate.getMonth();
    const daysInMonth = new Date(currentDate.getFullYear(), currentMonth + 1, 0).getDate();

    const daysArray = Array.from({ length: daysInMonth }, (_, index) => ({
      label: index + 1,
      value: index + 1,
    }));

    return daysArray;
  };

  const daysInCurrentMonth = getCurrentMonthDays();

  const dwmArray = [
    { label: 'Days', value: 'days' },
    { label: 'Weeks', value: 'weeks' },
    { label: 'Months', value: 'months' }
  ];



  const addMoreRow = () => {
    setAddMore(true);
  };

  const removeRow = () => {
    setAddMore(false);
  };


  const checkboxHandler = (event) => {
    setCheckedBox(e.target.value);
  };

  const handleMobileNumber = (e) => {
    setMobile(e.target.value);
    setIsEntering(e.target.value.length > 0);
  };

  const addMobileNumber = () => {
    setMobileList([...mobileList, { mob: mobile, checked: true }]);
    setIsEntering(false);
    setMobile('');

  };

  const hanldeMobileNumberCheck = (e, mobileNum) => {
    let updatedData;
    if (e.target.checked) {
      updatedData = mobileList.map(ele => (ele.mob === mobileNum ? { ...ele, checked: true } : ele));
    }
    else {
      updatedData = mobileList.map(ele => (ele.mob === mobileNum ? { ...ele, checked: false } : ele));
    }
    setMobileList(updatedData);
  };

  const handleDeleteNumbers = (val) => {
    const updatedList = mobileList.filter((e) => {
      return e.mob != val.mob;
    });
    setMobileList(updatedList);
  };

  return (
    <DashboardLayout>
      <DashboardNavbar />
      <SoftBox className="loyalty-config-next-btn-box">
        <SoftTypography variant="h4" fontSize="23px" fontWeight="bold" marginBottom="25px ">Loyalty Configuration</SoftTypography>
        <Button variant="contained" className="loyalty-config-next-btn" onClick={() => navigate('/new-loyalty-config/edit/review')}>Review Loyalty</Button>
      </SoftBox>
      <SoftBox className="channel-main-box">
        <SoftBox className="channel-phone-box">
          <img src={phone} alt="" />
        </SoftBox>
        <SoftBox className="channel-content-box">
          <SoftTypography variant="h4" fontSize="23px" fontWeight="bold">Get alerts for multiple orders generated by the same phone number</SoftTypography>
          <SoftBox className="multiple-order-container">
            <SoftBox className="loyalty-branding-box" my={1}>
              <SoftTypography variant="h4" fontSize="1rem" fontWeight="700">Multiple orders alert</SoftTypography>
              <Switch {...label} checked={checked} onChange={switchHandler} size="medium" />
            </SoftBox>
            <SoftBox sx={{ display: 'flex', justifyContent: 'flex-start' }}>
              <CircleNotificationsOutlinedIcon color="success" fontSize="medium" className="icon-margin" />
              <SoftTypography variant="h4" fontSize="1rem">An alert will be sent to your mobile number based on your selected channels <b className="multiple-text-highlight">everyday at 11 PM.</b></SoftTypography>
            </SoftBox>
            <SoftBox my={3} ml={0.5} display="flex" flexDirection="column" gap={1} className="input-container">
              <InputLabel required sx={{ fontWeight: 'bold', fontSize: '0.75rem', color: '#344767' }}>
                                Alert me when minimum of
              </InputLabel>
              <SoftBox style={{ width: '100%', display: 'flex', gap: '1rem' }} className={checked ? 'nonClickableDiv' : null}>
                <SoftSelect
                  options={daysInCurrentMonth}
                  className="loyalty-multiple-select"
                />
                <SoftSelect
                  options={dwmArray}
                  className="loyalty-multiple-days"
                />
              </SoftBox>
              {addMore ? <SoftBox style={{ width: '100%', display: 'flex', gap: '1rem' }} className={checked ? 'nonClickableDiv' : null} mt={2}>
                <SoftSelect
                  options={daysInCurrentMonth}
                  className="loyalty-multiple-select"
                />
                <SoftSelect
                  options={dwmArray}
                  className="loyalty-multiple-days"
                />
              </SoftBox> : null}
              <SoftBox sx={{ display: 'flex', justifyContent: 'space-between' }}>
                <SoftTypography variant="p" fontSize="15px">by a single phone number</SoftTypography>
                {!addMore ? <SoftTypography variant="p" fontSize="15px" onClick={addMoreRow} color="info">Add More</SoftTypography> :
                  <SoftTypography variant="p" fontSize="15px" onClick={removeRow} color="error">Remove</SoftTypography>}
              </SoftBox>
            </SoftBox>
          </SoftBox>
          <SoftBox className="multiple-order-container">
            <SoftBox className="channel-most-used">
              <SoftBox className="points-insp-box" mt={1}>
                <img src={bluestar} alt="" className="points-insp-image icon-margin" />
                <SoftTypography className="points-text-box">Most Preferred Channel</SoftTypography>
              </SoftBox>
              <SoftBox className="loyalty-multiple-checkbox-card no-padding" mt={1}>
                <SoftBox sx={{ display: 'flex', justifyContent: 'flex-start', alignItems: 'center' }}>
                  <WhatsAppIcon color="success" fontSize="medium" className="icon-margin" />
                  <SoftTypography variant="h4" fontSize="1rem" fontWeight="800">Whatsapp Utility</SoftTypography>
                </SoftBox>
                <Checkbox
                  {...label}
                  sx={{ '& .MuiSvgIcon-root': { fontSize: 28 } }}
                  value={checkedBox}
                  onChange={checkboxHandler}
                />
              </SoftBox>
            </SoftBox>
            <SoftBox className="loyalty-multiple-checkbox-card" mt={2}>
              <SoftBox sx={{ display: 'flex', justifyContent: 'flex-start', alignItems: 'center' }}>
                <SmsIcon color="primary" fontSize="medium" className="icon-margin" />
                <SoftTypography variant="h4" fontSize="1rem" fontWeight="800">SMS</SoftTypography>
              </SoftBox>
              <Checkbox
                {...label}
                sx={{ '& .MuiSvgIcon-root': { fontSize: 28 } }}
                value={checkedBox}
                onChange={checkboxHandler}
              />
            </SoftBox>
          </SoftBox>
          <SoftBox className="multiple-order-container">
            <SoftTypography variant="h4" fontSize="1rem" fontWeight="700">Mobile numbers to receive alerts</SoftTypography>
            <SoftTypography variant="p" fontSize="15px">These numbers won't be displayed anywhere.</SoftTypography>

            {mobileList.map((e) => (
              <SoftBox className="loyalty-multiple-checkbox-card">
                <SoftTypography variant="h4" fontSize="17px" fontWeight="bold" >{e.mob}</SoftTypography>
                <SoftBox sx={{ display: 'flex', justifyContent: 'flex-end' }}>
                  <Checkbox
                    {...label}
                    sx={{ '& .MuiSvgIcon-root': { fontSize: 28 } }}
                    value={e.checked}
                    onChange={(event) => hanldeMobileNumberCheck(event, e.mob)}
                    size="large"
                    defaultChecked={true}
                  />
                  {!e.checked ? <DeleteOutlineOutlinedIcon color="error" onClick={() => handleDeleteNumbers(e)} /> : null}
                </SoftBox>
              </SoftBox>
            ))}
            <SoftBox className="multiple-input-box">
              <input
                type="number"
                placeholder="Enter your number"
                style={{ maxHeight: '50px', border: 'none' }}
                className="multiple-input-tag"
                onChange={(e) => handleMobileNumber(e)}
                value={mobile}
              />
              {isEntering ? <button className="multiple-order-btn" onClick={addMobileNumber}>Add</button> : null}
            </SoftBox>
          </SoftBox>
        </SoftBox>
      </SoftBox>

    </DashboardLayout>
  );
};