import { CopyToClipBoard } from '../../../Common/CommonFunction';

export const productColumns = [
  {
    field: 'title',
    headerName: 'Title',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 200,
    flex: 1,
  },
  {
    field: 'barcode',
    headerName: 'Barcode',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 150,
    flex: 1,
    renderCell: (params) => {
      return <CopyToClipBoard params={params} />;
    },
  },
  {
    field: 'uom',
    headerName: 'UOM',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 50,
    flex: 1,
  },
  {
    field: 'mrp',
    headerName: 'MRP',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 70,
    flex: 1,
  },
  {
    field: 'stockInHand',
    headerName: 'Stock In Hand',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 70,
    flex: 1,
  },
  {
    field: 'location',
    headerName: 'Location',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 70,
    flex: 1,
  },
  {
    field: 'batches',
    headerName: 'Batches',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 130,
    flex: 1,
  },
  {
    field: 'incoming',
    headerName: 'Incoming',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 70,
    flex: 1,
  },
  {
    field: 'stockValue',
    headerName: 'Stock Value',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 70,
    flex: 1,
  },
];

// vendor
export const vendorColumns = [
  {
    field: 'vendor',
    headerName: 'Vendor',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 100,
    flex: 1,
  },
  {
    field: 'brands',
    headerName: 'Brands',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 150,
    flex: 1,
  },
  {
    field: 'location',
    headerName: 'Location',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 70,
    flex: 1,
  },
  {
    field: 'products',
    headerName: 'Products',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 70,
    flex: 1,
  },
  {
    field: 'lastPurchase',
    headerName: 'Last Purchase',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 70,
    flex: 1,
  },
  {
    field: 'incomingOrders',
    headerName: 'Incoming Orders',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 70,
    flex: 1,
  },
  {
    field: 'stockValue',
    headerName: 'Stock Value',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 130,
    flex: 1,
  },
];

// catgory
export const categoryColumns = [
  {
    field: 'category',
    headerName: 'Category',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 100,
    flex: 1,
  },
  {
    field: 'products',
    headerName: 'Products',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 150,
    flex: 1,
  },
  {
    field: 'wastage',
    headerName: 'Wastage Value',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 70,
    flex: 1,
  },
  {
    field: 'returns',
    headerName: 'Returns Value',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 70,
    flex: 1,
  },
  {
    field: 'incomingOrders',
    headerName: 'Incoming Orders',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 70,
    flex: 1,
  },
  {
    field: 'lastStockUpdate',
    headerName: 'Last Stock Update',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 70,
    flex: 1,
  },
  {
    field: 'stockValue',
    headerName: 'Stock Value',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 130,
    flex: 1,
  },
];

// brand
export const brandColumns = [
  {
    field: 'brand',
    headerName: 'Brand',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 100,
    flex: 1,
  },
  {
    field: 'products',
    headerName: 'Products',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 150,
    flex: 1,
  },
  {
    field: 'wastage',
    headerName: 'Wastage Value',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 70,
    flex: 1,
  },
  {
    field: 'returns',
    headerName: 'Returns Value',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 70,
    flex: 1,
  },
  {
    field: 'incomingOrders',
    headerName: 'Incoming Orders',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 70,
    flex: 1,
  },
  {
    field: 'lastStockUpdate',
    headerName: 'Last Stock Update',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 70,
    flex: 1,
  },
  {
    field: 'stockValue',
    headerName: 'Stock Value',
    headerClassName: 'datagrid-columns',
    headerAlign: 'left',
    cellClassName: 'datagrid-rows',
    align: 'left',
    minWidth: 130,
    flex: 1,
  },
];
