import { Box, Grid, Typography } from '@mui/material';
import { useNavigate, useParams } from 'react-router-dom';
import DashboardLayout from '../../../../examples/LayoutContainers/DashboardLayout';
import DashboardNavbar from '../../../../examples/Navbars/DashboardNavbar';
import React from 'react';
import SoftBox from '../../../../components/SoftBox';
import SoftButton from '../../../../components/SoftButton';

const StaticCouponDetails = () => {
  const navigate = useNavigate();
  const { id } = useParams();

  const handleImageError = (event) => {
    event.target.src = 'https://i.imgur.com/dL4ScuP.png';
  };

  return (
    <div>
      <DashboardLayout>
        <DashboardNavbar prevLink={true} />
        <SoftBox mb={2}>
          <SoftBox className="dynamic-coupon-journey-main-box" mb={2}>
            <Typography>Static Coupon</Typography>
            <SoftButton className="vendor-add-btn" onClick={() => navigate('/marketing/Coupons/static/create')}>
              Create
            </SoftButton>
          </SoftBox>
          <hr />
          <SoftBox mt={2}>
            <Grid container spacing={2}>
              <Grid item lg={6}>
                <Typography className="single-journey-title">
                  {id === 'cart'
                    ? 'Cart Value'
                    : id === 'product'
                      ? 'Product'
                      : id === 'preapproved'
                        ? 'Preapproved'
                        : ''}
                </Typography>
                <Typography className="single-journey-desc">
                  {id === 'cart'
                    ? 'The Cart value coupon applies to the total value of a customer\'s cart and according to the discount criteria applied that coupon code generated by you will be sent to the customer.'
                    : id === 'product'
                      ? 'The Product coupon applies to the customer if he/she buys the product set by you in the applying criteria and according to the set discount criteria that coupon will be enjoyed by the customer.'
                      : id === 'preapproved'
                        ? 'The Preapproved coupon is applied to a set of customers which come under a specific price slab as set by you and according to the discount criteria the generated coupon will be awarded to the customer if he/she meets the minimum cart value.'
                        : ''}
                </Typography>
                <Typography className="single-journey-points-start">Advantages:</Typography>
                <ul>
                  <li className="single-journey-points">
                    Serve as an incentive for new customers to try out products or services.
                  </li>
                  <li className="single-journey-points">
                    Can be easily distributed through various channels such as email, print media, or in-store.
                  </li>
                  <li className="single-journey-points">
                    Require minimal upkeep once created, saving time and effort.
                  </li>
                  <li className="single-journey-points">
                    Can be targeted towards promoting particular items or services effectively.
                  </li>
                </ul>
              </Grid>
              <Grid item lg={6}>
                <SoftBox className="single-journey-part2-box">
                  <Typography className="single-journey-part2-header">You'll need</Typography>
                  <Typography className="single-journey-part2-point">Pallet Subscription</Typography>
                  <Typography className="single-journey-part2-header">Journey Objective</Typography>
                  <Typography className="single-journey-part2-point">
                    Boosts sales and customer lifetime value
                  </Typography>
                </SoftBox>
              </Grid>
            </Grid>
            <Typography className="single-journey-points-start">Steps</Typography>
          </SoftBox>
          <Box className="table-css-fix-box-scroll-vend-1" id="box-shadow-1">
            <SoftBox className="dynamic-coupon-condtions-box1">
              {/* <div className="coupon-main-criteria-typo-box-1">
                <Typography className="single-journey-title-1">Coupon Redeeming Conditions</Typography>
              </div> */}
              <div className="dynamic-coupon-box-12345">
                <div className="dynamic-criteria-box">
                  <div className="dynamic-criteria-div">
                    <Typography className="single-journey-title-2">Applying criteria</Typography>
                  </div>
                  {id === 'product' ? (
                    <SoftBox className="dynamic-coupon-applying-criteria-box">
                      <div className="dynamic-coupon-applying-criteria-div-1">
                        <img
                          className="dynamic-coupon-applying-criteria-div-img"
                          onError={handleImageError}
                          src="https://storage.googleapis.com/twinleaves_bucket/FrontEnd/RMS_images/inflation_11162949.png"
                        />
                        <Typography className="single-journey-desc">Cart Value</Typography>
                      </div>
                      <div className="dynamic-coupon-applying-criteria-div-1">
                        <img
                          className="dynamic-coupon-applying-criteria-div-img"
                          src="https://storage.googleapis.com/twinleaves_bucket/FrontEnd/RMS_images/pantry_12391059.png"
                          onError={handleImageError}
                        />
                        <Typography className="single-journey-desc">Product</Typography>
                      </div>
                      <div className="dynamic-coupon-applying-criteria-div-1">
                        <img
                          className="dynamic-coupon-applying-criteria-div-img"
                          src="https://storage.googleapis.com/twinleaves_bucket/FrontEnd/RMS_images/food-basket_6104840.png"
                          onError={handleImageError}
                        />
                        <Typography className="single-journey-desc">Category</Typography>
                      </div>
                      <div className="dynamic-coupon-applying-criteria-div-1">
                        <img
                          className="dynamic-coupon-applying-criteria-div-img"
                          src="https://storage.googleapis.com/twinleaves_bucket/FrontEnd/RMS_images/brand-image_5334820.png"
                          onError={handleImageError}
                        />
                        <Typography className="single-journey-desc">Brand</Typography>
                      </div>
                      <div className="dynamic-coupon-applying-criteria-div-1">
                        <img
                          className="dynamic-coupon-applying-criteria-div-img"
                          src="https://storage.googleapis.com/twinleaves_bucket/FrontEnd/RMS_images/factory_1064295.png"
                          onError={handleImageError}
                        />
                        <Typography className="single-journey-desc">Manufacturer</Typography>
                      </div>
                    </SoftBox>
                  ) : id === 'cart' ? (
                    <SoftBox className="dynamic-coupon-applying-criteria-box-1">
                      <div className="dynamic-coupon-applying-criteria-div-1">
                        <img
                          className="dynamic-coupon-applying-criteria-div-img"
                          src="https://storage.googleapis.com/twinleaves_bucket/FrontEnd/RMS_images/inflation_11162949.png"
                          onError={handleImageError}
                        />
                        <Typography className="single-journey-desc">Minimum Cart Value</Typography>
                      </div>
                    </SoftBox>
                  ) : id === 'preapproved' ? (
                    <SoftBox className="dynamic-coupon-applying-criteria-box-1">
                      <div className="dynamic-coupon-applying-criteria-div-1">
                        <img
                          className="dynamic-coupon-applying-criteria-div-img"
                          src="https://storage.googleapis.com/twinleaves_bucket/FrontEnd/RMS_images/financial-advisor_8518520.png"
                          onError={handleImageError}
                        />
                        <Typography className="single-journey-desc">Customer Price Slab</Typography>
                      </div>
                      <div className="dynamic-coupon-applying-criteria-div-1">
                        <img
                          className="dynamic-coupon-applying-criteria-div-img"
                          src="https://storage.googleapis.com/twinleaves_bucket/FrontEnd/RMS_images/inflation_11162949.png"
                          onError={handleImageError}
                        />
                        <Typography className="single-journey-desc">Minimum Cart Value</Typography>
                      </div>
                    </SoftBox>
                  ) : null}
                </div>
                <div className="dynamic-criteria-box-2">
                  <div className="dynamic-criteria-div">
                    <Typography className="single-journey-title-2">Discount criteria</Typography>
                  </div>
                  <SoftBox className="dynamic-coupon-applying-criteria-box">
                    <div className="dynamic-coupon-applying-criteria-div-1">
                      <img
                        className="dynamic-coupon-applying-criteria-div-img"
                        src="https://storage.googleapis.com/twinleaves_bucket/FrontEnd/RMS_images/price-cut_9725525.png"
                        onError={handleImageError}
                      />
                      <Typography className="single-journey-desc">Discount</Typography>
                    </div>
                    <div className="dynamic-coupon-applying-criteria-div-1">
                      <img
                        className="dynamic-coupon-applying-criteria-div-img"
                        src="https://storage.googleapis.com/twinleaves_bucket/FrontEnd/RMS_images/bag_13759064.png"
                        onError={handleImageError}
                      />
                      <Typography className="single-journey-desc">Freebie</Typography>
                    </div>
                  </SoftBox>
                </div>
                <div className="dynamic-criteria-box" style={{ marginTop: '20px' }}>
                  <div className="dynamic-criteria-div">
                    <Typography className="single-journey-title-2">Terms and Conditions</Typography>
                  </div>
                  <SoftBox className="dynamic-coupon-applying-criteria-box">
                    <div className="dynamic-coupon-applying-criteria-div-1">
                      <img
                        className="dynamic-coupon-applying-criteria-div-img"
                        src="https://storage.googleapis.com/twinleaves_bucket/FrontEnd/RMS_images/inflation_11162949.png"
                        onError={handleImageError}
                      />
                      <Typography className="single-journey-desc">Min Cart Value</Typography>
                    </div>
                    <div className="dynamic-coupon-applying-criteria-div-1">
                      <img
                        className="dynamic-coupon-applying-criteria-div-img"
                        src="https://storage.googleapis.com/twinleaves_bucket/FrontEnd/RMS_images/map_854878.png"
                        onError={handleImageError}
                      />
                      <Typography className="single-journey-desc">Locations</Typography>
                    </div>
                    <div className="dynamic-coupon-applying-criteria-div-1">
                      <img
                        className="dynamic-coupon-applying-criteria-div-img"
                        src="https://storage.googleapis.com/twinleaves_bucket/FrontEnd/RMS_images/hourglass_492276.png"
                        onError={handleImageError}
                      />
                      <Typography className="single-journey-desc">Validity</Typography>
                    </div>
                    <div className="dynamic-coupon-applying-criteria-div-1">
                      <img
                        className="dynamic-coupon-applying-criteria-div-img"
                        src="https://storage.googleapis.com/twinleaves_bucket/FrontEnd/RMS_images/mobile-payment_2715823.png"
                        onError={handleImageError}
                      />
                      <Typography className="single-journey-desc">Sales Channel</Typography>
                    </div>
                  </SoftBox>
                </div>
              </div>
            </SoftBox>
          </Box>
        </SoftBox>
      </DashboardLayout>
    </div>
  );
};

export default StaticCouponDetails;
