export const city = [
  { label: 'Kolhapur', value: 'Maharashtra' },
  { label: 'Port Blair', value: 'Andaman & Nicobar Islands' },
  { label: 'Adilabad', value: 'Andhra Pradesh' },
  { label: 'Adoni', value: 'Andhra Pradesh' },
  { label: 'Amadalavalasa', value: 'Andhra Pradesh' },
  { label: 'Amalapuram', value: 'Andhra Pradesh' },
  { label: 'Anakapalle', value: 'Andhra Pradesh' },
  { label: 'Anantapur', value: 'Andhra Pradesh' },
  { label: 'Badepalle', value: 'Andhra Pradesh' },
  { label: 'Banganapalle', value: 'Andhra Pradesh' },
  { label: 'Bapatla', value: 'Andhra Pradesh' },
  { label: 'Bellampalle', value: 'Andhra Pradesh' },
  { label: 'Bethamcherla', value: 'Andhra Pradesh' },
  { label: 'Bhadrachalam', value: 'Andhra Pradesh' },
  { label: 'Bhainsa', value: 'Andhra Pradesh' },
  { label: 'Bheemunipatnam', value: 'Andhra Pradesh' },
  { label: 'Bhimavaram', value: 'Andhra Pradesh' },
  { label: 'Bhongir', value: 'Andhra Pradesh' },
  { label: 'Bobbili', value: 'Andhra Pradesh' },
  { label: 'Bodhan', value: 'Andhra Pradesh' },
  { label: 'Chilakaluripet', value: 'Andhra Pradesh' },
  { label: 'Chirala', value: 'Andhra Pradesh' },
  { label: 'Chittoor', value: 'Andhra Pradesh' },
  { label: 'Cuddapah', value: 'Andhra Pradesh' },
  { label: 'Devarakonda', value: 'Andhra Pradesh' },
  { label: 'Dharmavaram', value: 'Andhra Pradesh' },
  { label: 'Eluru', value: 'Andhra Pradesh' },
  { label: 'Farooqnagar', value: 'Andhra Pradesh' },
  { label: 'Gadwal', value: 'Andhra Pradesh' },
  { label: 'Gooty', value: 'Andhra Pradesh' },
  { label: 'Gudivada', value: 'Andhra Pradesh' },
  { label: 'Gudur', value: 'Andhra Pradesh' },
  { label: 'Guntakal', value: 'Andhra Pradesh' },
  { label: 'Guntur', value: 'Andhra Pradesh' },
  { label: 'Hanuman Junction', value: 'Andhra Pradesh' },
  { label: 'Hindupur', value: 'Andhra Pradesh' },
  { label: 'Hyderabad', value: 'Andhra Pradesh' },
  { label: 'Ichchapuram', value: 'Andhra Pradesh' },
  { label: 'Jaggaiahpet', value: 'Andhra Pradesh' },
  { label: 'Jagtial', value: 'Andhra Pradesh' },
  { label: 'Jammalamadugu', value: 'Andhra Pradesh' },
  { label: 'Jangaon', value: 'Andhra Pradesh' },
  { label: 'Kadapa', value: 'Andhra Pradesh' },
  { label: 'Kadiri', value: 'Andhra Pradesh' },
  { label: 'Kagaznagar', value: 'Andhra Pradesh' },
  { label: 'Kakinada', value: 'Andhra Pradesh' },
  { label: 'Kalyandurg', value: 'Andhra Pradesh' },
  { label: 'Kamareddy', value: 'Andhra Pradesh' },
  { label: 'Kandukur', value: 'Andhra Pradesh' },
  { label: 'Karimnagar', value: 'Andhra Pradesh' },
  { label: 'Kavali', value: 'Andhra Pradesh' },
  { label: 'Khammam', value: 'Andhra Pradesh' },
  { label: 'Koratla', value: 'Andhra Pradesh' },
  { label: 'Kothagudem', value: 'Andhra Pradesh' },
  { label: 'Kothapeta', value: 'Andhra Pradesh' },
  { label: 'Kovvur', value: 'Andhra Pradesh' },
  { label: 'Kurnool', value: 'Andhra Pradesh' },
  { label: 'Kyathampalle', value: 'Andhra Pradesh' },
  { label: 'Macherla', value: 'Andhra Pradesh' },
  { label: 'Machilipatnam', value: 'Andhra Pradesh' },
  { label: 'Madanapalle', value: 'Andhra Pradesh' },
  { label: 'Mahbubnagar', value: 'Andhra Pradesh' },
  { label: 'Mancherial', value: 'Andhra Pradesh' },
  { label: 'Mandamarri', value: 'Andhra Pradesh' },
  { label: 'Mandapeta', value: 'Andhra Pradesh' },
  { label: 'Manuguru', value: 'Andhra Pradesh' },
  { label: 'Markapur', value: 'Andhra Pradesh' },
  { label: 'Medak', value: 'Andhra Pradesh' },
  { label: 'Miryalaguda', value: 'Andhra Pradesh' },
  { label: 'Mogalthur', value: 'Andhra Pradesh' },
  { label: 'Nagari', value: 'Andhra Pradesh' },
  { label: 'Nagarkurnool', value: 'Andhra Pradesh' },
  { label: 'Nandyal', value: 'Andhra Pradesh' },
  { label: 'Narasapur', value: 'Andhra Pradesh' },
  { label: 'Narasaraopet', value: 'Andhra Pradesh' },
  { label: 'Narayanpet', value: 'Andhra Pradesh' },
  { label: 'Narsipatnam', value: 'Andhra Pradesh' },
  { label: 'Nellore', value: 'Andhra Pradesh' },
  { label: 'Nidadavole', value: 'Andhra Pradesh' },
  { label: 'Nirmal', value: 'Andhra Pradesh' },
  { label: 'Nizamabad', value: 'Andhra Pradesh' },
  { label: 'Nuzvid', value: 'Andhra Pradesh' },
  { label: 'Ongole', value: 'Andhra Pradesh' },
  { label: 'Palacole', value: 'Andhra Pradesh' },
  { label: 'Palasa Kasibugga', value: 'Andhra Pradesh' },
  { label: 'Palwancha', value: 'Andhra Pradesh' },
  { label: 'Parvathipuram', value: 'Andhra Pradesh' },
  { label: 'Pedana', value: 'Andhra Pradesh' },
  { label: 'Peddapuram', value: 'Andhra Pradesh' },
  { label: 'Pithapuram', value: 'Andhra Pradesh' },
  { label: 'Pondur', value: 'Andhra pradesh' },
  { label: 'Ponnur', value: 'Andhra Pradesh' },
  { label: 'Proddatur', value: 'Andhra Pradesh' },
  { label: 'Punganur', value: 'Andhra Pradesh' },
  { label: 'Puttur', value: 'Andhra Pradesh' },
  { label: 'Rajahmundry', value: 'Andhra Pradesh' },
  { label: 'Rajam', value: 'Andhra Pradesh' },
  { label: 'Ramachandrapuram', value: 'Andhra Pradesh' },
  { label: 'Ramagundam', value: 'Andhra Pradesh' },
  { label: 'Rayachoti', value: 'Andhra Pradesh' },
  { label: 'Rayadurg', value: 'Andhra Pradesh' },
  { label: 'Renigunta', value: 'Andhra Pradesh' },
  { label: 'Repalle', value: 'Andhra Pradesh' },
  { label: 'Sadasivpet', value: 'Andhra Pradesh' },
  { label: 'Salur', value: 'Andhra Pradesh' },
  { label: 'Samalkot', value: 'Andhra Pradesh' },
  { label: 'Sangareddy', value: 'Andhra Pradesh' },
  { label: 'Sattenapalle', value: 'Andhra Pradesh' },
  { label: 'Siddipet', value: 'Andhra Pradesh' },
  { label: 'Singapur', value: 'Andhra Pradesh' },
  { label: 'Sircilla', value: 'Andhra Pradesh' },
  { label: 'Srikakulam', value: 'Andhra Pradesh' },
  { label: 'Srikalahasti', value: 'Andhra Pradesh' },
  { label: 'Suryapet', value: 'Andhra Pradesh' },
  { label: 'Tadepalligudem', value: 'Andhra Pradesh' },
  { label: 'Tadpatri', value: 'Andhra Pradesh' },
  { label: 'Tandur', value: 'Andhra Pradesh' },
  { label: 'Tanuku', value: 'Andhra Pradesh' },
  { label: 'Tenali', value: 'Andhra Pradesh' },
  { label: 'Tirupati', value: 'Andhra Pradesh' },
  { label: 'Tuni', value: 'Andhra Pradesh' },
  { label: 'Uravakonda', value: 'Andhra Pradesh' },
  { label: 'Venkatagiri', value: 'Andhra Pradesh' },
  { label: 'Vicarabad', value: 'Andhra Pradesh' },
  { label: 'Vijayawada', value: 'Andhra Pradesh' },
  { label: 'Vinukonda', value: 'Andhra Pradesh' },
  { label: 'Visakhapatnam', value: 'Andhra Pradesh' },
  { label: 'Vizianagaram', value: 'Andhra Pradesh' },
  { label: 'Wanaparthy', value: 'Andhra Pradesh' },
  { label: 'Warangal', value: 'Andhra Pradesh' },
  { label: 'Yellandu', value: 'Andhra Pradesh' },
  { label: 'Yemmiganur', value: 'Andhra Pradesh' },
  { label: 'Yerraguntla', value: 'Andhra Pradesh' },
  { label: 'Zahirabad', value: 'Andhra Pradesh' },
  { label: 'Rajampet', value: 'Andhra Pradesh' },
  { label: 'Along', value: 'Arunachal Pradesh' },
  { label: 'Bomdila', value: 'Arunachal Pradesh' },
  { label: 'Itanagar', value: 'Arunachal Pradesh' },
  { label: 'Naharlagun', value: 'Arunachal Pradesh' },
  { label: 'Pasighat', value: 'Arunachal Pradesh' },
  { label: 'Abhayapuri', value: 'Assam' },
  { label: 'Amguri', value: 'Assam' },
  { label: 'Anandnagaar', value: 'Assam' },
  { label: 'Barpeta', value: 'Assam' },
  { label: 'Barpeta Road', value: 'Assam' },
  { label: 'Bilasipara', value: 'Assam' },
  { label: 'Bongaigaon', value: 'Assam' },
  { label: 'Dhekiajuli', value: 'Assam' },
  { label: 'Dhubri', value: 'Assam' },
  { label: 'Dibrugarh', value: 'Assam' },
  { label: 'Digboi', value: 'Assam' },
  { label: 'Diphu', value: 'Assam' },
  { label: 'Dispur', value: 'Assam' },
  { label: 'Gauripur', value: 'Assam' },
  { label: 'Goalpara', value: 'Assam' },
  { label: 'Golaghat', value: 'Assam' },
  { label: 'Guwahati', value: 'Assam' },
  { label: 'Haflong', value: 'Assam' },
  { label: 'Hailakandi', value: 'Assam' },
  { label: 'Hojai', value: 'Assam' },
  { label: 'Jorhat', value: 'Assam' },
  { label: 'Karimganj', value: 'Assam' },
  { label: 'Kokrajhar', value: 'Assam' },
  { label: 'Lanka', value: 'Assam' },
  { label: 'Lumding', value: 'Assam' },
  { label: 'Mangaldoi', value: 'Assam' },
  { label: 'Mankachar', value: 'Assam' },
  { label: 'Margherita', value: 'Assam' },
  { label: 'Mariani', value: 'Assam' },
  { label: 'Marigaon', value: 'Assam' },
  { label: 'Nagaon', value: 'Assam' },
  { label: 'Nalbari', value: 'Assam' },
  { label: 'North Lakhimpur', value: 'Assam' },
  { label: 'Rangia', value: 'Assam' },
  { label: 'Sibsagar', value: 'Assam' },
  { label: 'Silapathar', value: 'Assam' },
  { label: 'Silchar', value: 'Assam' },
  { label: 'Tezpur', value: 'Assam' },
  { label: 'Tinsukia', value: 'Assam' },
  { label: 'Amarpur', value: 'Bihar' },
  { label: 'Araria', value: 'Bihar' },
  { label: 'Areraj', value: 'Bihar' },
  { label: 'Arrah', value: 'Bihar' },
  { label: 'Asarganj', value: 'Bihar' },
  { label: 'Aurangabad', value: 'Bihar' },
  { label: 'Bagaha', value: 'Bihar' },
  { label: 'Bahadurganj', value: 'Bihar' },
  { label: 'Bairgania', value: 'Bihar' },
  { label: 'Bakhtiarpur', value: 'Bihar' },
  { label: 'Banka', value: 'Bihar' },
  { label: 'Banmankhi Bazar', value: 'Bihar' },
  { label: 'Barahiya', value: 'Bihar' },
  { label: 'Barauli', value: 'Bihar' },
  { label: 'Barbigha', value: 'Bihar' },
  { label: 'Barh', value: 'Bihar' },
  { label: 'Begusarai', value: 'Bihar' },
  { label: 'Behea', value: 'Bihar' },
  { label: 'Bettiah', value: 'Bihar' },
  { label: 'Bhabua', value: 'Bihar' },
  { label: 'Bhagalpur', value: 'Bihar' },
  { label: 'Bihar Sharif', value: 'Bihar' },
  { label: 'Bikramganj', value: 'Bihar' },
  { label: 'Bodh Gaya', value: 'Bihar' },
  { label: 'Buxar', value: 'Bihar' },
  { label: 'Chandan Bara', value: 'Bihar' },
  { label: 'Chanpatia', value: 'Bihar' },
  { label: 'Chhapra', value: 'Bihar' },
  { label: 'Colgong', value: 'Bihar' },
  { label: 'Dalsinghsarai', value: 'Bihar' },
  { label: 'Darbhanga', value: 'Bihar' },
  { label: 'Daudnagar', value: 'Bihar' },
  { label: 'Dehri-on-Sone', value: 'Bihar' },
  { label: 'Dhaka', value: 'Bihar' },
  { label: 'Dighwara', value: 'Bihar' },
  { label: 'Dumraon', value: 'Bihar' },
  { label: 'Fatwah', value: 'Bihar' },
  { label: 'Forbesganj', value: 'Bihar' },
  { label: 'Gaya', value: 'Bihar' },
  { label: 'Gogri Jamalpur', value: 'Bihar' },
  { label: 'Gopalganj', value: 'Bihar' },
  { label: 'Hajipur', value: 'Bihar' },
  { label: 'Hilsa', value: 'Bihar' },
  { label: 'Hisua', value: 'Bihar' },
  { label: 'Islampur', value: 'Bihar' },
  { label: 'Jagdispur', value: 'Bihar' },
  { label: 'Jamalpur', value: 'Bihar' },
  { label: 'Jamui', value: 'Bihar' },
  { label: 'Jehanabad', value: 'Bihar' },
  { label: 'Jhajha', value: 'Bihar' },
  { label: 'Jhanjharpur', value: 'Bihar' },
  { label: 'Jogabani', value: 'Bihar' },
  { label: 'Kanti', value: 'Bihar' },
  { label: 'Katihar', value: 'Bihar' },
  { label: 'Khagaria', value: 'Bihar' },
  { label: 'Kharagpur', value: 'Bihar' },
  { label: 'Kishanganj', value: 'Bihar' },
  { label: 'Lakhisarai', value: 'Bihar' },
  { label: 'Lalganj', value: 'Bihar' },
  { label: 'Madhepura', value: 'Bihar' },
  { label: 'Madhubani', value: 'Bihar' },
  { label: 'Maharajganj', value: 'Bihar' },
  { label: 'Mahnar Bazar', value: 'Bihar' },
  { label: 'Makhdumpur', value: 'Bihar' },
  { label: 'Maner', value: 'Bihar' },
  { label: 'Manihari', value: 'Bihar' },
  { label: 'Marhaura', value: 'Bihar' },
  { label: 'Masaurhi', value: 'Bihar' },
  { label: 'Mirganj', value: 'Bihar' },
  { label: 'Mokameh', value: 'Bihar' },
  { label: 'Motihari', value: 'Bihar' },
  { label: 'Motipur', value: 'Bihar' },
  { label: 'Munger', value: 'Bihar' },
  { label: 'Murliganj', value: 'Bihar' },
  { label: 'Muzaffarpur', value: 'Bihar' },
  { label: 'Narkatiaganj', value: 'Bihar' },
  { label: 'Naugachhia', value: 'Bihar' },
  { label: 'Nawada', value: 'Bihar' },
  { label: 'Nokha', value: 'Bihar' },
  { label: 'Patna', value: 'Bihar' },
  { label: 'Piro', value: 'Bihar' },
  { label: 'Purnia', value: 'Bihar' },
  { label: 'Rafiganj', value: 'Bihar' },
  { label: 'Rajgir', value: 'Bihar' },
  { label: 'Ramnagar', value: 'Bihar' },
  { label: 'Raxaul Bazar', value: 'Bihar' },
  { label: 'Revelganj', value: 'Bihar' },
  { label: 'Rosera', value: 'Bihar' },
  { label: 'Saharsa', value: 'Bihar' },
  { label: 'Samastipur', value: 'Bihar' },
  { label: 'Sasaram', value: 'Bihar' },
  { label: 'Sheikhpura', value: 'Bihar' },
  { label: 'Sheohar', value: 'Bihar' },
  { label: 'Sherghati', value: 'Bihar' },
  { label: 'Silao', value: 'Bihar' },
  { label: 'Sitamarhi', value: 'Bihar' },
  { label: 'Siwan', value: 'Bihar' },
  { label: 'Sonepur', value: 'Bihar' },
  { label: 'Sugauli', value: 'Bihar' },
  { label: 'Sultanganj', value: 'Bihar' },
  { label: 'Supaul', value: 'Bihar' },
  { label: 'Warisaliganj', value: 'Bihar' },
  { label: 'Ahiwara', value: 'Chhattisgarh' },
  { label: 'Akaltara', value: 'Chhattisgarh' },
  { label: 'Ambagarh Chowki', value: 'Chhattisgarh' },
  { label: 'Ambikapur', value: 'Chhattisgarh' },
  { label: 'Arang', value: 'Chhattisgarh' },
  { label: 'Bade Bacheli', value: 'Chhattisgarh' },
  { label: 'Balod', value: 'Chhattisgarh' },
  { label: 'Baloda Bazar', value: 'Chhattisgarh' },
  { label: 'Bemetra', value: 'Chhattisgarh' },
  { label: 'Bhatapara', value: 'Chhattisgarh' },
  { label: 'Bilaspur', value: 'Chhattisgarh' },
  { label: 'Birgaon', value: 'Chhattisgarh' },
  { label: 'Champa', value: 'Chhattisgarh' },
  { label: 'Chirmiri', value: 'Chhattisgarh' },
  { label: 'Dalli-Rajhara', value: 'Chhattisgarh' },
  { label: 'Dhamtari', value: 'Chhattisgarh' },
  { label: 'Dipka', value: 'Chhattisgarh' },
  { label: 'Dongargarh', value: 'Chhattisgarh' },
  { label: 'Durg-Bhilai Nagar', value: 'Chhattisgarh' },
  { label: 'Gobranawapara', value: 'Chhattisgarh' },
  { label: 'Jagdalpur', value: 'Chhattisgarh' },
  { label: 'Janjgir', value: 'Chhattisgarh' },
  { label: 'Jashpurnagar', value: 'Chhattisgarh' },
  { label: 'Kanker', value: 'Chhattisgarh' },
  { label: 'Kawardha', value: 'Chhattisgarh' },
  { label: 'Kondagaon', value: 'Chhattisgarh' },
  { label: 'Korba', value: 'Chhattisgarh' },
  { label: 'Mahasamund', value: 'Chhattisgarh' },
  { label: 'Mahendragarh', value: 'Chhattisgarh' },
  { label: 'Mungeli', value: 'Chhattisgarh' },
  { label: 'Naila Janjgir', value: 'Chhattisgarh' },
  { label: 'Raigarh', value: 'Chhattisgarh' },
  { label: 'Raipur', value: 'Chhattisgarh' },
  { label: 'Rajnandgaon', value: 'Chhattisgarh' },
  { label: 'Sakti', value: 'Chhattisgarh' },
  { label: 'Tilda Newra', value: 'Chhattisgarh' },
  { label: 'Amli', value: 'Dadra & Nagar Haveli' },
  { label: 'Silvassa', value: 'Dadra & Nagar Haveli' },
  { label: 'Daman and Diu', value: 'Daman & Diu' },
  { label: 'Daman and Diu', value: 'Daman & Diu' },
  { label: 'Asola', value: 'Delhi' },
  { label: 'Delhi', value: 'Delhi' },
  { label: 'Aldona', value: 'Goa' },
  { label: 'Curchorem Cacora', value: 'Goa' },
  { label: 'Madgaon', value: 'Goa' },
  { label: 'Mapusa', value: 'Goa' },
  { label: 'Margao', value: 'Goa' },
  { label: 'Marmagao', value: 'Goa' },
  { label: 'Panaji', value: 'Goa' },
  { label: 'Ahmedabad', value: 'Gujarat' },
  { label: 'Amreli', value: 'Gujarat' },
  { label: 'Anand', value: 'Gujarat' },
  { label: 'Ankleshwar', value: 'Gujarat' },
  { label: 'Bharuch', value: 'Gujarat' },
  { label: 'Bhavnagar', value: 'Gujarat' },
  { label: 'Bhuj', value: 'Gujarat' },
  { label: 'Cambay', value: 'Gujarat' },
  { label: 'Dahod', value: 'Gujarat' },
  { label: 'Deesa', value: 'Gujarat' },
  { label: 'Dharampur', value: ' India' },
  { label: 'Dholka', value: 'Gujarat' },
  { label: 'Gandhinagar', value: 'Gujarat' },
  { label: 'Godhra', value: 'Gujarat' },
  { label: 'Himatnagar', value: 'Gujarat' },
  { label: 'Idar', value: 'Gujarat' },
  { label: 'Jamnagar', value: 'Gujarat' },
  { label: 'Junagadh', value: 'Gujarat' },
  { label: 'Kadi', value: 'Gujarat' },
  { label: 'Kalavad', value: 'Gujarat' },
  { label: 'Kalol', value: 'Gujarat' },
  { label: 'Kapadvanj', value: 'Gujarat' },
  { label: 'Karjan', value: 'Gujarat' },
  { label: 'Keshod', value: 'Gujarat' },
  { label: 'Khambhalia', value: 'Gujarat' },
  { label: 'Khambhat', value: 'Gujarat' },
  { label: 'Kheda', value: 'Gujarat' },
  { label: 'Khedbrahma', value: 'Gujarat' },
  { label: 'Kheralu', value: 'Gujarat' },
  { label: 'Kodinar', value: 'Gujarat' },
  { label: 'Lathi', value: 'Gujarat' },
  { label: 'Limbdi', value: 'Gujarat' },
  { label: 'Lunawada', value: 'Gujarat' },
  { label: 'Mahesana', value: 'Gujarat' },
  { label: 'Mahuva', value: 'Gujarat' },
  { label: 'Manavadar', value: 'Gujarat' },
  { label: 'Mandvi', value: 'Gujarat' },
  { label: 'Mangrol', value: 'Gujarat' },
  { label: 'Mansa', value: 'Gujarat' },
  { label: 'Mehmedabad', value: 'Gujarat' },
  { label: 'Modasa', value: 'Gujarat' },
  { label: 'Morvi', value: 'Gujarat' },
  { label: 'Nadiad', value: 'Gujarat' },
  { label: 'Navsari', value: 'Gujarat' },
  { label: 'Padra', value: 'Gujarat' },
  { label: 'Palanpur', value: 'Gujarat' },
  { label: 'Palitana', value: 'Gujarat' },
  { label: 'Pardi', value: 'Gujarat' },
  { label: 'Patan', value: 'Gujarat' },
  { label: 'Petlad', value: 'Gujarat' },
  { label: 'Porbandar', value: 'Gujarat' },
  { label: 'Radhanpur', value: 'Gujarat' },
  { label: 'Rajkot', value: 'Gujarat' },
  { label: 'Rajpipla', value: 'Gujarat' },
  { label: 'Rajula', value: 'Gujarat' },
  { label: 'Ranavav', value: 'Gujarat' },
  { label: 'Rapar', value: 'Gujarat' },
  { label: 'Salaya', value: 'Gujarat' },
  { label: 'Sanand', value: 'Gujarat' },
  { label: 'Savarkundla', value: 'Gujarat' },
  { label: 'Sidhpur', value: 'Gujarat' },
  { label: 'Sihor', value: 'Gujarat' },
  { label: 'Songadh', value: 'Gujarat' },
  { label: 'Surat', value: 'Gujarat' },
  { label: 'Talaja', value: 'Gujarat' },
  { label: 'Thangadh', value: 'Gujarat' },
  { label: 'Tharad', value: 'Gujarat' },
  { label: 'Umbergaon', value: 'Gujarat' },
  { label: 'Umreth', value: 'Gujarat' },
  { label: 'Una', value: 'Gujarat' },
  { label: 'Unjha', value: 'Gujarat' },
  { label: 'Upleta', value: 'Gujarat' },
  { label: 'Vadnagar', value: 'Gujarat' },
  { label: 'Vadodara', value: 'Gujarat' },
  { label: 'Valsad', value: 'Gujarat' },
  { label: 'Vapi', value: 'Gujarat' },
  { label: 'Vapi', value: 'Gujarat' },
  { label: 'Veraval', value: 'Gujarat' },
  { label: 'Vijapur', value: 'Gujarat' },
  { label: 'Viramgam', value: 'Gujarat' },
  { label: 'Visnagar', value: 'Gujarat' },
  { label: 'Vyara', value: 'Gujarat' },
  { label: 'Wadhwan', value: 'Gujarat' },
  { label: 'Wankaner', value: 'Gujarat' },
  { label: 'Adalaj', value: 'Gujrat' },
  { label: 'Adityana', value: 'Gujrat' },
  { label: 'Alang', value: 'Gujrat' },
  { label: 'Ambaji', value: 'Gujrat' },
  { label: 'Ambaliyasan', value: 'Gujrat' },
  { label: 'Andada', value: 'Gujrat' },
  { label: 'Anjar', value: 'Gujrat' },
  { label: 'Anklav', value: 'Gujrat' },
  { label: 'Antaliya', value: 'Gujrat' },
  { label: 'Arambhada', value: 'Gujrat' },
  { label: 'Atul', value: 'Gujrat' },
  { label: 'Ballabhgarh', value: 'Hariyana' },
  { label: 'Ambala', value: 'Haryana' },
  { label: 'Ambala', value: 'Haryana' },
  { label: 'Asankhurd', value: 'Haryana' },
  { label: 'Assandh', value: 'Haryana' },
  { label: 'Ateli', value: 'Haryana' },
  { label: 'Babiyal', value: 'Haryana' },
  { label: 'Bahadurgarh', value: 'Haryana' },
  { label: 'Barwala', value: 'Haryana' },
  { label: 'Bhiwani', value: 'Haryana' },
  { label: 'Charkhi Dadri', value: 'Haryana' },
  { label: 'Cheeka', value: 'Haryana' },
  { label: 'Ellenabad 2', value: 'Haryana' },
  { label: 'Faridabad', value: 'Haryana' },
  { label: 'Fatehabad', value: 'Haryana' },
  { label: 'Ganaur', value: 'Haryana' },
  { label: 'Gharaunda', value: 'Haryana' },
  { label: 'Gohana', value: 'Haryana' },
  { label: 'Gurgaon', value: 'Haryana' },
  { label: 'Haibat(Yamuna Nagar)', value: 'Haryana' },
  { label: 'Hansi', value: 'Haryana' },
  { label: 'Hisar', value: 'Haryana' },
  { label: 'Hodal', value: 'Haryana' },
  { label: 'Jhajjar', value: 'Haryana' },
  { label: 'Jind', value: 'Haryana' },
  { label: 'Kaithal', value: 'Haryana' },
  { label: 'Kalan Wali', value: 'Haryana' },
  { label: 'Kalka', value: 'Haryana' },
  { label: 'Karnal', value: 'Haryana' },
  { label: 'Ladwa', value: 'Haryana' },
  { label: 'Mahendragarh', value: 'Haryana' },
  { label: 'Mandi Dabwali', value: 'Haryana' },
  { label: 'Narnaul', value: 'Haryana' },
  { label: 'Narwana', value: 'Haryana' },
  { label: 'Palwal', value: 'Haryana' },
  { label: 'Panchkula', value: 'Haryana' },
  { label: 'Panipat', value: 'Haryana' },
  { label: 'Pehowa', value: 'Haryana' },
  { label: 'Pinjore', value: 'Haryana' },
  { label: 'Rania', value: 'Haryana' },
  { label: 'Ratia', value: 'Haryana' },
  { label: 'Rewari', value: 'Haryana' },
  { label: 'Rohtak', value: 'Haryana' },
  { label: 'Safidon', value: 'Haryana' },
  { label: 'Samalkha', value: 'Haryana' },
  { label: 'Shahbad', value: 'Haryana' },
  { label: 'Sirsa', value: 'Haryana' },
  { label: 'Sohna', value: 'Haryana' },
  { label: 'Sonipat', value: 'Haryana' },
  { label: 'Taraori', value: 'Haryana' },
  { label: 'Thanesar', value: 'Haryana' },
  { label: 'Tohana', value: 'Haryana' },
  { label: 'Yamunanagar', value: 'Haryana' },
  { label: 'Arki', value: 'Himachal Pradesh' },
  { label: 'Baddi', value: 'Himachal Pradesh' },
  { label: 'Bilaspur', value: 'Himachal Pradesh' },
  { label: 'Chamba', value: 'Himachal Pradesh' },
  { label: 'Dalhousie', value: 'Himachal Pradesh' },
  { label: 'Dharamsala', value: 'Himachal Pradesh' },
  { label: 'Hamirpur', value: 'Himachal Pradesh' },
  { label: 'Mandi', value: 'Himachal Pradesh' },
  { label: 'Nahan', value: 'Himachal Pradesh' },
  { label: 'Shimla', value: 'Himachal Pradesh' },
  { label: 'Solan', value: 'Himachal Pradesh' },
  { label: 'Sundarnagar', value: 'Himachal Pradesh' },
  { label: 'Jammu', value: 'Jammu & Kashmir' },
  { label: 'Achabbal', value: 'Jammu & Kashmir' },
  { label: 'Akhnoor', value: 'Jammu & Kashmir' },
  { label: 'Anantnag', value: 'Jammu & Kashmir' },
  { label: 'Arnia', value: 'Jammu & Kashmir' },
  { label: 'Awantipora', value: 'Jammu & Kashmir' },
  { label: 'Bandipore', value: 'Jammu & Kashmir' },
  { label: 'Baramula', value: 'Jammu & Kashmir' },
  { label: 'Kathua', value: 'Jammu & Kashmir' },
  { label: 'Leh', value: 'Jammu & Kashmir' },
  { label: 'Punch', value: 'Jammu & Kashmir' },
  { label: 'Rajauri', value: 'Jammu & Kashmir' },
  { label: 'Sopore', value: 'Jammu & Kashmir' },
  { label: 'Srinagar', value: 'Jammu & Kashmir' },
  { label: 'Udhampur', value: 'Jammu & Kashmir' },
  { label: 'Amlabad', value: 'Jharkhand' },
  { label: 'Ara', value: 'Jharkhand' },
  { label: 'Barughutu', value: 'Jharkhand' },
  { label: 'Bokaro Steel label', value: 'Jharkhand' },
  { label: 'Chaibasa', value: 'Jharkhand' },
  { label: 'Chakradharpur', value: 'Jharkhand' },
  { label: 'Chandrapura', value: 'Jharkhand' },
  { label: 'Chatra', value: 'Jharkhand' },
  { label: 'Chirkunda', value: 'Jharkhand' },
  { label: 'Churi', value: 'Jharkhand' },
  { label: 'Daltonganj', value: 'Jharkhand' },
  { label: 'Deoghar', value: 'Jharkhand' },
  { label: 'Dhanbad', value: 'Jharkhand' },
  { label: 'Dumka', value: 'Jharkhand' },
  { label: 'Garhwa', value: 'Jharkhand' },
  { label: 'Ghatshila', value: 'Jharkhand' },
  { label: 'Giridih', value: 'Jharkhand' },
  { label: 'Godda', value: 'Jharkhand' },
  { label: 'Gomoh', value: 'Jharkhand' },
  { label: 'Gumia', value: 'Jharkhand' },
  { label: 'Gumla', value: 'Jharkhand' },
  { label: 'Hazaribag', value: 'Jharkhand' },
  { label: 'Hussainabad', value: 'Jharkhand' },
  { label: 'Jamshedpur', value: 'Jharkhand' },
  { label: 'Jamtara', value: 'Jharkhand' },
  { label: 'Jhumri Tilaiya', value: 'Jharkhand' },
  { label: 'Khunti', value: 'Jharkhand' },
  { label: 'Lohardaga', value: 'Jharkhand' },
  { label: 'Madhupur', value: 'Jharkhand' },
  { label: 'Mihijam', value: 'Jharkhand' },
  { label: 'Musabani', value: 'Jharkhand' },
  { label: 'Pakaur', value: 'Jharkhand' },
  { label: 'Patratu', value: 'Jharkhand' },
  { label: 'Phusro', value: 'Jharkhand' },
  { label: 'Ramngarh', value: 'Jharkhand' },
  { label: 'Ranchi', value: 'Jharkhand' },
  { label: 'Sahibganj', value: 'Jharkhand' },
  { label: 'Saunda', value: 'Jharkhand' },
  { label: 'Simdega', value: 'Jharkhand' },
  { label: 'Tenu Dam-cum- Kathhara', value: 'Jharkhand' },
  { label: 'Arasikere', value: 'Karnataka' },
  { label: 'Bangalore', value: 'Karnataka' },
  { label: 'Belgaum', value: 'Karnataka' },
  { label: 'Bellary', value: 'Karnataka' },
  { label: 'Chamrajnagar', value: 'Karnataka' },
  { label: 'Chikkaballapur', value: 'Karnataka' },
  { label: 'Chintamani', value: 'Karnataka' },
  { label: 'Chitradurga', value: 'Karnataka' },
  { label: 'Gulbarga', value: 'Karnataka' },
  { label: 'Gundlupet', value: 'Karnataka' },
  { label: 'Hassan', value: 'Karnataka' },
  { label: 'Hospet', value: 'Karnataka' },
  { label: 'Hubli', value: 'Karnataka' },
  { label: 'Karkala', value: 'Karnataka' },
  { label: 'Karwar', value: 'Karnataka' },
  { label: 'Kolar', value: 'Karnataka' },
  { label: 'Kota', value: 'Karnataka' },
  { label: 'Lakshmeshwar', value: 'Karnataka' },
  { label: 'Lingsugur', value: 'Karnataka' },
  { label: 'Maddur', value: 'Karnataka' },
  { label: 'Madhugiri', value: 'Karnataka' },
  { label: 'Madikeri', value: 'Karnataka' },
  { label: 'Magadi', value: 'Karnataka' },
  { label: 'Mahalingpur', value: 'Karnataka' },
  { label: 'Malavalli', value: 'Karnataka' },
  { label: 'Malur', value: 'Karnataka' },
  { label: 'Mandya', value: 'Karnataka' },
  { label: 'Mangalore', value: 'Karnataka' },
  { label: 'Manvi', value: 'Karnataka' },
  { label: 'Mudalgi', value: 'Karnataka' },
  { label: 'Mudbidri', value: 'Karnataka' },
  { label: 'Muddebihal', value: 'Karnataka' },
  { label: 'Mudhol', value: 'Karnataka' },
  { label: 'Mulbagal', value: 'Karnataka' },
  { label: 'Mundargi', value: 'Karnataka' },
  { label: 'Mysore', value: 'Karnataka' },
  { label: 'Nanjangud', value: 'Karnataka' },
  { label: 'Pavagada', value: 'Karnataka' },
  { label: 'Puttur', value: 'Karnataka' },
  { label: 'Rabkavi Banhatti', value: 'Karnataka' },
  { label: 'Raichur', value: 'Karnataka' },
  { label: 'Ramanagaram', value: 'Karnataka' },
  { label: 'Ramdurg', value: 'Karnataka' },
  { label: 'Ranibennur', value: 'Karnataka' },
  { label: 'Robertson Pet', value: 'Karnataka' },
  { label: 'Ron', value: 'Karnataka' },
  { label: 'Sadalgi', value: 'Karnataka' },
  { label: 'Sagar', value: 'Karnataka' },
  { label: 'Sakleshpur', value: 'Karnataka' },
  { label: 'Sandur', value: 'Karnataka' },
  { label: 'Sankeshwar', value: 'Karnataka' },
  { label: 'Saundatti-Yellamma', value: 'Karnataka' },
  { label: 'Savanur', value: 'Karnataka' },
  { label: 'Sedam', value: 'Karnataka' },
  { label: 'Shahabad', value: 'Karnataka' },
  { label: 'Shahpur', value: 'Karnataka' },
  { label: 'Shiggaon', value: 'Karnataka' },
  { label: 'Shikapur', value: 'Karnataka' },
  { label: 'Shimoga', value: 'Karnataka' },
  { label: 'Shorapur', value: 'Karnataka' },
  { label: 'Shrirangapattana', value: 'Karnataka' },
  { label: 'Sidlaghatta', value: 'Karnataka' },
  { label: 'Sindgi', value: 'Karnataka' },
  { label: 'Sindhnur', value: 'Karnataka' },
  { label: 'Sira', value: 'Karnataka' },
  { label: 'Sirsi', value: 'Karnataka' },
  { label: 'Siruguppa', value: 'Karnataka' },
  { label: 'Srinivaspur', value: 'Karnataka' },
  { label: 'Talikota', value: 'Karnataka' },
  { label: 'Tarikere', value: 'Karnataka' },
  { label: 'Tekkalakota', value: 'Karnataka' },
  { label: 'Terdal', value: 'Karnataka' },
  { label: 'Tiptur', value: 'Karnataka' },
  { label: 'Tumkur', value: 'Karnataka' },
  { label: 'Udupi', value: 'Karnataka' },
  { label: 'Vijayapura', value: 'Karnataka' },
  { label: 'Wadi', value: 'Karnataka' },
  { label: 'Yadgir', value: 'Karnataka' },
  { label: 'Adoor', value: 'Kerala' },
  { label: 'Akathiyoor', value: 'Kerala' },
  { label: 'Alappuzha', value: 'Kerala' },
  { label: 'Ancharakandy', value: 'Kerala' },
  { label: 'Aroor', value: 'Kerala' },
  { label: 'Ashtamichira', value: 'Kerala' },
  { label: 'Attingal', value: 'Kerala' },
  { label: 'Avinissery', value: 'Kerala' },
  { label: 'Chalakudy', value: 'Kerala' },
  { label: 'Changanassery', value: 'Kerala' },
  { label: 'Chendamangalam', value: 'Kerala' },
  { label: 'Chengannur', value: 'Kerala' },
  { label: 'Cherthala', value: 'Kerala' },
  { label: 'Cheruthazham', value: 'Kerala' },
  { label: 'Chittur-Thathamangalam', value: 'Kerala' },
  { label: 'Chockli', value: 'Kerala' },
  { label: 'Erattupetta', value: 'Kerala' },
  { label: 'Guruvayoor', value: 'Kerala' },
  { label: 'Irinjalakuda', value: 'Kerala' },
  { label: 'Kadirur', value: 'Kerala' },
  { label: 'Kalliasseri', value: 'Kerala' },
  { label: 'Kalpetta', value: 'Kerala' },
  { label: 'Kanhangad', value: 'Kerala' },
  { label: 'Kanjikkuzhi', value: 'Kerala' },
  { label: 'Kannur', value: 'Kerala' },
  { label: 'Kasaragod', value: 'Kerala' },
  { label: 'Kayamkulam', value: 'Kerala' },
  { label: 'Kochi', value: 'Kerala' },
  { label: 'Kodungallur', value: 'Kerala' },
  { label: 'Kollam', value: 'Kerala' },
  { label: 'Koothuparamba', value: 'Kerala' },
  { label: 'Kothamangalam', value: 'Kerala' },
  { label: 'Kottayam', value: 'Kerala' },
  { label: 'Kozhikode', value: 'Kerala' },
  { label: 'Kunnamkulam', value: 'Kerala' },
  { label: 'Malappuram', value: 'Kerala' },
  { label: 'Mattannur', value: 'Kerala' },
  { label: 'Mavelikkara', value: 'Kerala' },
  { label: 'Mavoor', value: 'Kerala' },
  { label: 'Muvattupuzha', value: 'Kerala' },
  { label: 'Nedumangad', value: 'Kerala' },
  { label: 'Neyyattinkara', value: 'Kerala' },
  { label: 'Ottappalam', value: 'Kerala' },
  { label: 'Palai', value: 'Kerala' },
  { label: 'Palakkad', value: 'Kerala' },
  { label: 'Panniyannur', value: 'Kerala' },
  { label: 'Pappinisseri', value: 'Kerala' },
  { label: 'Paravoor', value: 'Kerala' },
  { label: 'Pathanamthitta', value: 'Kerala' },
  { label: 'Payyannur', value: 'Kerala' },
  { label: 'Peringathur', value: 'Kerala' },
  { label: 'Perinthalmanna', value: 'Kerala' },
  { label: 'Perumbavoor', value: 'Kerala' },
  { label: 'Ponnani', value: 'Kerala' },
  { label: 'Punalur', value: 'Kerala' },
  { label: 'Quilandy', value: 'Kerala' },
  { label: 'Shoranur', value: 'Kerala' },
  { label: 'Taliparamba', value: 'Kerala' },
  { label: 'Thiruvalla', value: 'Kerala' },
  { label: 'Thiruvananthapuram', value: 'Kerala' },
  { label: 'Thodupuzha', value: 'Kerala' },
  { label: 'Thrissur', value: 'Kerala' },
  { label: 'Tirur', value: 'Kerala' },
  { label: 'Vadakara', value: 'Kerala' },
  { label: 'Vaikom', value: 'Kerala' },
  { label: 'Varkala', value: 'Kerala' },
  { label: 'Kavaratti', value: 'Lakshadweep' },
  { label: 'Ashok Nagar', value: 'Madhya Pradesh' },
  { label: 'Balaghat', value: 'Madhya Pradesh' },
  { label: 'Betul', value: 'Madhya Pradesh' },
  { label: 'Bhopal', value: 'Madhya Pradesh' },
  { label: 'Burhanpur', value: 'Madhya Pradesh' },
  { label: 'Chhatarpur', value: 'Madhya Pradesh' },
  { label: 'Dabra', value: 'Madhya Pradesh' },
  { label: 'Datia', value: 'Madhya Pradesh' },
  { label: 'Dewas', value: 'Madhya Pradesh' },
  { label: 'Dhar', value: 'Madhya Pradesh' },
  { label: 'Fatehabad', value: 'Madhya Pradesh' },
  { label: 'Gwalior', value: 'Madhya Pradesh' },
  { label: 'Indore', value: 'Madhya Pradesh' },
  { label: 'Itarsi', value: 'Madhya Pradesh' },
  { label: 'Jabalpur', value: 'Madhya Pradesh' },
  { label: 'Katni', value: 'Madhya Pradesh' },
  { label: 'Kotma', value: 'Madhya Pradesh' },
  { label: 'Lahar', value: 'Madhya Pradesh' },
  { label: 'Lundi', value: 'Madhya Pradesh' },
  { label: 'Maharajpur', value: 'Madhya Pradesh' },
  { label: 'Mahidpur', value: 'Madhya Pradesh' },
  { label: 'Maihar', value: 'Madhya Pradesh' },
  { label: 'Malajkhand', value: 'Madhya Pradesh' },
  { label: 'Manasa', value: 'Madhya Pradesh' },
  { label: 'Manawar', value: 'Madhya Pradesh' },
  { label: 'Mandideep', value: 'Madhya Pradesh' },
  { label: 'Mandla', value: 'Madhya Pradesh' },
  { label: 'Mandsaur', value: 'Madhya Pradesh' },
  { label: 'Mauganj', value: 'Madhya Pradesh' },
  { label: 'Mhow Cantonment', value: 'Madhya Pradesh' },
  { label: 'Mhowgaon', value: 'Madhya Pradesh' },
  { label: 'Morena', value: 'Madhya Pradesh' },
  { label: 'Multai', value: 'Madhya Pradesh' },
  { label: 'Murwara', value: 'Madhya Pradesh' },
  { label: 'Nagda', value: 'Madhya Pradesh' },
  { label: 'Nainpur', value: 'Madhya Pradesh' },
  { label: 'Narsinghgarh', value: 'Madhya Pradesh' },
  { label: 'Narsinghgarh', value: 'Madhya Pradesh' },
  { label: 'Neemuch', value: 'Madhya Pradesh' },
  { label: 'Nepanagar', value: 'Madhya Pradesh' },
  { label: 'Niwari', value: 'Madhya Pradesh' },
  { label: 'Nowgong', value: 'Madhya Pradesh' },
  { label: 'Nowrozabad', value: 'Madhya Pradesh' },
  { label: 'Pachore', value: 'Madhya Pradesh' },
  { label: 'Pali', value: 'Madhya Pradesh' },
  { label: 'Panagar', value: 'Madhya Pradesh' },
  { label: 'Pandhurna', value: 'Madhya Pradesh' },
  { label: 'Panna', value: 'Madhya Pradesh' },
  { label: 'Pasan', value: 'Madhya Pradesh' },
  { label: 'Pipariya', value: 'Madhya Pradesh' },
  { label: 'Pithampur', value: 'Madhya Pradesh' },
  { label: 'Porsa', value: 'Madhya Pradesh' },
  { label: 'Prithvipur', value: 'Madhya Pradesh' },
  { label: 'Raghogarh-Vijaypur', value: 'Madhya Pradesh' },
  { label: 'Rahatgarh', value: 'Madhya Pradesh' },
  { label: 'Raisen', value: 'Madhya Pradesh' },
  { label: 'Rajgarh', value: 'Madhya Pradesh' },
  { label: 'Ratlam', value: 'Madhya Pradesh' },
  { label: 'Rau', value: 'Madhya Pradesh' },
  { label: 'Rehli', value: 'Madhya Pradesh' },
  { label: 'Rewa', value: 'Madhya Pradesh' },
  { label: 'Sabalgarh', value: 'Madhya Pradesh' },
  { label: 'Sagar', value: 'Madhya Pradesh' },
  { label: 'Sanawad', value: 'Madhya Pradesh' },
  { label: 'Sarangpur', value: 'Madhya Pradesh' },
  { label: 'Sarni', value: 'Madhya Pradesh' },
  { label: 'Satna', value: 'Madhya Pradesh' },
  { label: 'Sausar', value: 'Madhya Pradesh' },
  { label: 'Sehore', value: 'Madhya Pradesh' },
  { label: 'Sendhwa', value: 'Madhya Pradesh' },
  { label: 'Seoni', value: 'Madhya Pradesh' },
  { label: 'Seoni-Malwa', value: 'Madhya Pradesh' },
  { label: 'Shahdol', value: 'Madhya Pradesh' },
  { label: 'Shajapur', value: 'Madhya Pradesh' },
  { label: 'Shamgarh', value: 'Madhya Pradesh' },
  { label: 'Sheopur', value: 'Madhya Pradesh' },
  { label: 'Shivpuri', value: 'Madhya Pradesh' },
  { label: 'Shujalpur', value: 'Madhya Pradesh' },
  { label: 'Sidhi', value: 'Madhya Pradesh' },
  { label: 'Sihora', value: 'Madhya Pradesh' },
  { label: 'Singrauli', value: 'Madhya Pradesh' },
  { label: 'Sironj', value: 'Madhya Pradesh' },
  { label: 'Sohagpur', value: 'Madhya Pradesh' },
  { label: 'Tarana', value: 'Madhya Pradesh' },
  { label: 'Tikamgarh', value: 'Madhya Pradesh' },
  { label: 'Ujhani', value: 'Madhya Pradesh' },
  { label: 'Ujjain', value: 'Madhya Pradesh' },
  { label: 'Umaria', value: 'Madhya Pradesh' },
  { label: 'Vidisha', value: 'Madhya Pradesh' },
  { label: 'Wara Seoni', value: 'Madhya Pradesh' },
  { label: 'Ahmednagar', value: 'Maharashtra' },
  { label: 'Akola', value: 'Maharashtra' },
  { label: 'Amravati', value: 'Maharashtra' },
  { label: 'Aurangabad', value: 'Maharashtra' },
  { label: 'Baramati', value: 'Maharashtra' },
  { label: 'Chalisgaon', value: 'Maharashtra' },
  { label: 'Chinchani', value: 'Maharashtra' },
  { label: 'Devgarh', value: 'Maharashtra' },
  { label: 'Dhule', value: 'Maharashtra' },
  { label: 'Dombivli', value: 'Maharashtra' },
  { label: 'Durgapur', value: 'Maharashtra' },
  { label: 'Ichalkaranji', value: 'Maharashtra' },
  { label: 'Jalna', value: 'Maharashtra' },
  { label: 'Kalyan', value: 'Maharashtra' },
  { label: 'Latur', value: 'Maharashtra' },
  { label: 'Loha', value: 'Maharashtra' },
  { label: 'Lonar', value: 'Maharashtra' },
  { label: 'Lonavla', value: 'Maharashtra' },
  { label: 'Mahad', value: 'Maharashtra' },
  { label: 'Mahuli', value: 'Maharashtra' },
  { label: 'Malegaon', value: 'Maharashtra' },
  { label: 'Malkapur', value: 'Maharashtra' },
  { label: 'Manchar', value: 'Maharashtra' },
  { label: 'Mangalvedhe', value: 'Maharashtra' },
  { label: 'Mangrulpir', value: 'Maharashtra' },
  { label: 'Manjlegaon', value: 'Maharashtra' },
  { label: 'Manmad', value: 'Maharashtra' },
  { label: 'Manwath', value: 'Maharashtra' },
  { label: 'Mehkar', value: 'Maharashtra' },
  { label: 'Mhaswad', value: 'Maharashtra' },
  { label: 'Miraj', value: 'Maharashtra' },
  { label: 'Morshi', value: 'Maharashtra' },
  { label: 'Mukhed', value: 'Maharashtra' },
  { label: 'Mul', value: 'Maharashtra' },
  { label: 'Mumbai', value: 'Maharashtra' },
  { label: 'Murtijapur', value: 'Maharashtra' },
  { label: 'Nagpur', value: 'Maharashtra' },
  { label: 'Nalasopara', value: 'Maharashtra' },
  { label: 'Nanded-Waghala', value: 'Maharashtra' },
  { label: 'Nandgaon', value: 'Maharashtra' },
  { label: 'Nandura', value: 'Maharashtra' },
  { label: 'Nandurbar', value: 'Maharashtra' },
  { label: 'Narkhed', value: 'Maharashtra' },
  { label: 'Nashik', value: 'Maharashtra' },
  { label: 'Navi Mumbai', value: 'Maharashtra' },
  { label: 'Nawapur', value: 'Maharashtra' },
  { label: 'Nilanga', value: 'Maharashtra' },
  { label: 'Osmanabad', value: 'Maharashtra' },
  { label: 'Ozar', value: 'Maharashtra' },
  { label: 'Pachora', value: 'Maharashtra' },
  { label: 'Paithan', value: 'Maharashtra' },
  { label: 'Palghar', value: 'Maharashtra' },
  { label: 'Pandharkaoda', value: 'Maharashtra' },
  { label: 'Pandharpur', value: 'Maharashtra' },
  { label: 'Panvel', value: 'Maharashtra' },
  { label: 'Parbhani', value: 'Maharashtra' },
  { label: 'Parli', value: 'Maharashtra' },
  { label: 'Parola', value: 'Maharashtra' },
  { label: 'Partur', value: 'Maharashtra' },
  { label: 'Pathardi', value: 'Maharashtra' },
  { label: 'Pathri', value: 'Maharashtra' },
  { label: 'Patur', value: 'Maharashtra' },
  { label: 'Pauni', value: 'Maharashtra' },
  { label: 'Pen', value: 'Maharashtra' },
  { label: 'Phaltan', value: 'Maharashtra' },
  { label: 'Pulgaon', value: 'Maharashtra' },
  { label: 'Pune', value: 'Maharashtra' },
  { label: 'Purna', value: 'Maharashtra' },
  { label: 'Pusad', value: 'Maharashtra' },
  { label: 'Rahuri', value: 'Maharashtra' },
  { label: 'Rajura', value: 'Maharashtra' },
  { label: 'Ramtek', value: 'Maharashtra' },
  { label: 'Ratnagiri', value: 'Maharashtra' },
  { label: 'Raver', value: 'Maharashtra' },
  { label: 'Risod', value: 'Maharashtra' },
  { label: 'Sailu', value: 'Maharashtra' },
  { label: 'Sangamner', value: 'Maharashtra' },
  { label: 'Sangli', value: 'Maharashtra' },
  { label: 'Sangole', value: 'Maharashtra' },
  { label: 'Sasvad', value: 'Maharashtra' },
  { label: 'Satana', value: 'Maharashtra' },
  { label: 'Satara', value: 'Maharashtra' },
  { label: 'Savner', value: 'Maharashtra' },
  { label: 'Sawantwadi', value: 'Maharashtra' },
  { label: 'Shahade', value: 'Maharashtra' },
  { label: 'Shegaon', value: 'Maharashtra' },
  { label: 'Shendurjana', value: 'Maharashtra' },
  { label: 'Shirdi', value: 'Maharashtra' },
  { label: 'Shirpur-Warwade', value: 'Maharashtra' },
  { label: 'Shirur', value: 'Maharashtra' },
  { label: 'Shrigonda', value: 'Maharashtra' },
  { label: 'Shrirampur', value: 'Maharashtra' },
  { label: 'Sillod', value: 'Maharashtra' },
  { label: 'Sinnar', value: 'Maharashtra' },
  { label: 'Solapur', value: 'Maharashtra' },
  { label: 'Soyagaon', value: 'Maharashtra' },
  { label: 'Talegaon Dabhade', value: 'Maharashtra' },
  { label: 'Talode', value: 'Maharashtra' },
  { label: 'Tasgaon', value: 'Maharashtra' },
  { label: 'Tirora', value: 'Maharashtra' },
  { label: 'Tuljapur', value: 'Maharashtra' },
  { label: 'Tumsar', value: 'Maharashtra' },
  { label: 'Uran', value: 'Maharashtra' },
  { label: 'Uran Islampur', value: 'Maharashtra' },
  { label: 'Wadgaon Road', value: 'Maharashtra' },
  { label: 'Wai', value: 'Maharashtra' },
  { label: 'Wani', value: 'Maharashtra' },
  { label: 'Wardha', value: 'Maharashtra' },
  { label: 'Warora', value: 'Maharashtra' },
  { label: 'Warud', value: 'Maharashtra' },
  { label: 'Washim', value: 'Maharashtra' },
  { label: 'Yevla', value: 'Maharashtra' },
  { label: 'Uchgaon', value: 'Maharashtra' },
  { label: 'Udgir', value: 'Maharashtra' },
  { label: 'Umarga', value: 'Maharastra' },
  { label: 'Umarkhed', value: 'Maharastra' },
  { label: 'Umred', value: 'Maharastra' },
  { label: 'Vadgaon Kasba', value: 'Maharastra' },
  { label: 'Vaijapur', value: 'Maharastra' },
  { label: 'Vasai', value: 'Maharastra' },
  { label: 'Virar', value: 'Maharastra' },
  { label: 'Vita', value: 'Maharastra' },
  { label: 'Yavatmal', value: 'Maharastra' },
  { label: 'Yawal', value: 'Maharastra' },
  { label: 'Imphal', value: 'Manipur' },
  { label: 'Kakching', value: 'Manipur' },
  { label: 'Lilong', value: 'Manipur' },
  { label: 'Mayang Imphal', value: 'Manipur' },
  { label: 'Thoubal', value: 'Manipur' },
  { label: 'Jowai', value: 'Meghalaya' },
  { label: 'Nongstoin', value: 'Meghalaya' },
  { label: 'Shillong', value: 'Meghalaya' },
  { label: 'Tura', value: 'Meghalaya' },
  { label: 'Aizawl', value: 'Mizoram' },
  { label: 'Champhai', value: 'Mizoram' },
  { label: 'Lunglei', value: 'Mizoram' },
  { label: 'Saiha', value: 'Mizoram' },
  { label: 'Dimapur', value: 'Nagaland' },
  { label: 'Kohima', value: 'Nagaland' },
  { label: 'Mokokchung', value: 'Nagaland' },
  { label: 'Tuensang', value: 'Nagaland' },
  { label: 'Wokha', value: 'Nagaland' },
  { label: 'Zunheboto', value: 'Nagaland' },
  { label: 'Anandapur', value: 'Orissa' },
  { label: 'Anugul', value: 'Orissa' },
  { label: 'Asika', value: 'Orissa' },
  { label: 'Balangir', value: 'Orissa' },
  { label: 'Balasore', value: 'Orissa' },
  { label: 'Baleshwar', value: 'Orissa' },
  { label: 'Bamra', value: 'Orissa' },
  { label: 'Barbil', value: 'Orissa' },
  { label: 'Bargarh', value: 'Orissa' },
  { label: 'Bargarh', value: 'Orissa' },
  { label: 'Baripada', value: 'Orissa' },
  { label: 'Basudebpur', value: 'Orissa' },
  { label: 'Belpahar', value: 'Orissa' },
  { label: 'Bhadrak', value: 'Orissa' },
  { label: 'Bhawanipatna', value: 'Orissa' },
  { label: 'Bhuban', value: 'Orissa' },
  { label: 'Bhubaneswar', value: 'Orissa' },
  { label: 'Biramitrapur', value: 'Orissa' },
  { label: 'Brahmapur', value: 'Orissa' },
  { label: 'Brajrajnagar', value: 'Orissa' },
  { label: 'Byasanagar', value: 'Orissa' },
  { label: 'Cuttack', value: 'Orissa' },
  { label: 'Debagarh', value: 'Orissa' },
  { label: 'Dhenkanal', value: 'Orissa' },
  { label: 'Gunupur', value: 'Orissa' },
  { label: 'Hinjilicut', value: 'Orissa' },
  { label: 'Jagatsinghapur', value: 'Orissa' },
  { label: 'Jajapur', value: 'Orissa' },
  { label: 'Jaleswar', value: 'Orissa' },
  { label: 'Jatani', value: 'Orissa' },
  { label: 'Jeypur', value: 'Orissa' },
  { label: 'Jharsuguda', value: 'Orissa' },
  { label: 'Joda', value: 'Orissa' },
  { label: 'Kantabanji', value: 'Orissa' },
  { label: 'Karanjia', value: 'Orissa' },
  { label: 'Kendrapara', value: 'Orissa' },
  { label: 'Kendujhar', value: 'Orissa' },
  { label: 'Khordha', value: 'Orissa' },
  { label: 'Koraput', value: 'Orissa' },
  { label: 'Malkangiri', value: 'Orissa' },
  { label: 'Nabarangapur', value: 'Orissa' },
  { label: 'Paradip', value: 'Orissa' },
  { label: 'Parlakhemundi', value: 'Orissa' },
  { label: 'Pattamundai', value: 'Orissa' },
  { label: 'Phulabani', value: 'Orissa' },
  { label: 'Puri', value: 'Orissa' },
  { label: 'Rairangpur', value: 'Orissa' },
  { label: 'Rajagangapur', value: 'Orissa' },
  { label: 'Raurkela', value: 'Orissa' },
  { label: 'Rayagada', value: 'Orissa' },
  { label: 'Sambalpur', value: 'Orissa' },
  { label: 'Soro', value: 'Orissa' },
  { label: 'Sunabeda', value: 'Orissa' },
  { label: 'Sundargarh', value: 'Orissa' },
  { label: 'Talcher', value: 'Orissa' },
  { label: 'Titlagarh', value: 'Orissa' },
  { label: 'Umarkote', value: 'Orissa' },
  { label: 'Karaikal', value: 'Pondicherry' },
  { label: 'Mahe', value: 'Pondicherry' },
  { label: 'Pondicherry', value: 'Pondicherry' },
  { label: 'Yanam', value: 'Pondicherry' },
  { label: 'Ahmedgarh', value: 'Punjab' },
  { label: 'Amritsar', value: 'Punjab' },
  { label: 'Barnala', value: 'Punjab' },
  { label: 'Batala', value: 'Punjab' },
  { label: 'Bathinda', value: 'Punjab' },
  { label: 'Bhagha Purana', value: 'Punjab' },
  { label: 'Budhlada', value: 'Punjab' },
  { label: 'Chandigarh', value: 'Punjab' },
  { label: 'Dasua', value: 'Punjab' },
  { label: 'Dhuri', value: 'Punjab' },
  { label: 'Dinanagar', value: 'Punjab' },
  { label: 'Faridkot', value: 'Punjab' },
  { label: 'Fazilka', value: 'Punjab' },
  { label: 'Firozpur', value: 'Punjab' },
  { label: 'Firozpur Cantt.', value: 'Punjab' },
  { label: 'Giddarbaha', value: 'Punjab' },
  { label: 'Gobindgarh', value: 'Punjab' },
  { label: 'Gurdaspur', value: 'Punjab' },
  { label: 'Hoshiarpur', value: 'Punjab' },
  { label: 'Jagraon', value: 'Punjab' },
  { label: 'Jaitu', value: 'Punjab' },
  { label: 'Jalalabad', value: 'Punjab' },
  { label: 'Jalandhar', value: 'Punjab' },
  { label: 'Jalandhar Cantt.', value: 'Punjab' },
  { label: 'Jandiala', value: 'Punjab' },
  { label: 'Kapurthala', value: 'Punjab' },
  { label: 'Karoran', value: 'Punjab' },
  { label: 'Kartarpur', value: 'Punjab' },
  { label: 'Khanna', value: 'Punjab' },
  { label: 'Kharar', value: 'Punjab' },
  { label: 'Kot Kapura', value: 'Punjab' },
  { label: 'Kurali', value: 'Punjab' },
  { label: 'Longowal', value: 'Punjab' },
  { label: 'Ludhiana', value: 'Punjab' },
  { label: 'Malerkotla', value: 'Punjab' },
  { label: 'Malout', value: 'Punjab' },
  { label: 'Mansa', value: 'Punjab' },
  { label: 'Maur', value: 'Punjab' },
  { label: 'Moga', value: 'Punjab' },
  { label: 'Mohali', value: 'Punjab' },
  { label: 'Morinda', value: 'Punjab' },
  { label: 'Mukerian', value: 'Punjab' },
  { label: 'Muktsar', value: 'Punjab' },
  { label: 'Nabha', value: 'Punjab' },
  { label: 'Nakodar', value: 'Punjab' },
  { label: 'Nangal', value: 'Punjab' },
  { label: 'Nawanshahr', value: 'Punjab' },
  { label: 'Pathankot', value: 'Punjab' },
  { label: 'Patiala', value: 'Punjab' },
  { label: 'Patran', value: 'Punjab' },
  { label: 'Patti', value: 'Punjab' },
  { label: 'Phagwara', value: 'Punjab' },
  { label: 'Phillaur', value: 'Punjab' },
  { label: 'Qadian', value: 'Punjab' },
  { label: 'Raikot', value: 'Punjab' },
  { label: 'Rajpura', value: 'Punjab' },
  { label: 'Rampura Phul', value: 'Punjab' },
  { label: 'Rupnagar', value: 'Punjab' },
  { label: 'Samana', value: 'Punjab' },
  { label: 'Sangrur', value: 'Punjab' },
  { label: 'Sirhind Fatehgarh Sahib', value: 'Punjab' },
  { label: 'Sujanpur', value: 'Punjab' },
  { label: 'Sunam', value: 'Punjab' },
  { label: 'Talwara', value: 'Punjab' },
  { label: 'Tarn Taran', value: 'Punjab' },
  { label: 'Urmar Tanda', value: 'Punjab' },
  { label: 'Zira', value: 'Punjab' },
  { label: 'Zirakpur', value: 'Punjab' },
  { label: 'Bali', value: 'Rajasthan' },
  { label: 'Banswara', value: 'Rajastan' },
  { label: 'Ajmer', value: 'Rajasthan' },
  { label: 'Alwar', value: 'Rajasthan' },
  { label: 'Bandikui', value: 'Rajasthan' },
  { label: 'Baran', value: 'Rajasthan' },
  { label: 'Barmer', value: 'Rajasthan' },
  { label: 'Bikaner', value: 'Rajasthan' },
  { label: 'Fatehpur', value: 'Rajasthan' },
  { label: 'Jaipur', value: 'Rajasthan' },
  { label: 'Jaisalmer', value: 'Rajasthan' },
  { label: 'Jodhpur', value: 'Rajasthan' },
  { label: 'Kota', value: 'Rajasthan' },
  { label: 'Lachhmangarh', value: 'Rajasthan' },
  { label: 'Ladnu', value: 'Rajasthan' },
  { label: 'Lakheri', value: 'Rajasthan' },
  { label: 'Lalsot', value: 'Rajasthan' },
  { label: 'Losal', value: 'Rajasthan' },
  { label: 'Makrana', value: 'Rajasthan' },
  { label: 'Malpura', value: 'Rajasthan' },
  { label: 'Mandalgarh', value: 'Rajasthan' },
  { label: 'Mandawa', value: 'Rajasthan' },
  { label: 'Mangrol', value: 'Rajasthan' },
  { label: 'Merta label', value: 'Rajasthan' },
  { label: 'Mount Abu', value: 'Rajasthan' },
  { label: 'Nadbai', value: 'Rajasthan' },
  { label: 'Nagar', value: 'Rajasthan' },
  { label: 'Nagaur', value: 'Rajasthan' },
  { label: 'Nargund', value: 'Rajasthan' },
  { label: 'Nasirabad', value: 'Rajasthan' },
  { label: 'Nathdwara', value: 'Rajasthan' },
  { label: 'Navalgund', value: 'Rajasthan' },
  { label: 'Nawalgarh', value: 'Rajasthan' },
  { label: 'Neem-Ka-Thana', value: 'Rajasthan' },
  { label: 'Nelamangala', value: 'Rajasthan' },
  { label: 'Nimbahera', value: 'Rajasthan' },
  { label: 'Nipani', value: 'Rajasthan' },
  { label: 'Niwai', value: 'Rajasthan' },
  { label: 'Nohar', value: 'Rajasthan' },
  { label: 'Nokha', value: 'Rajasthan' },
  { label: 'Pali', value: 'Rajasthan' },
  { label: 'Phalodi', value: 'Rajasthan' },
  { label: 'Phulera', value: 'Rajasthan' },
  { label: 'Pilani', value: 'Rajasthan' },
  { label: 'Pilibanga', value: 'Rajasthan' },
  { label: 'Pindwara', value: 'Rajasthan' },
  { label: 'Pipar label', value: 'Rajasthan' },
  { label: 'Prantij', value: 'Rajasthan' },
  { label: 'Pratapgarh', value: 'Rajasthan' },
  { label: 'Raisinghnagar', value: 'Rajasthan' },
  { label: 'Rajakhera', value: 'Rajasthan' },
  { label: 'Rajaldesar', value: 'Rajasthan' },
  { label: 'Rajgarh (Alwar)', value: 'Rajasthan' },
  { label: 'Rajgarh (Churu', value: 'Rajasthan' },
  { label: 'Rajsamand', value: 'Rajasthan' },
  { label: 'Ramganj Mandi', value: 'Rajasthan' },
  { label: 'Ramngarh', value: 'Rajasthan' },
  { label: 'Ratangarh', value: 'Rajasthan' },
  { label: 'Rawatbhata', value: 'Rajasthan' },
  { label: 'Rawatsar', value: 'Rajasthan' },
  { label: 'Reengus', value: 'Rajasthan' },
  { label: 'Sadri', value: 'Rajasthan' },
  { label: 'Sadulshahar', value: 'Rajasthan' },
  { label: 'Sagwara', value: 'Rajasthan' },
  { label: 'Sambhar', value: 'Rajasthan' },
  { label: 'Sanchore', value: 'Rajasthan' },
  { label: 'Sangaria', value: 'Rajasthan' },
  { label: 'Sardarshahar', value: 'Rajasthan' },
  { label: 'Sawai Madhopur', value: 'Rajasthan' },
  { label: 'Shahpura', value: 'Rajasthan' },
  { label: 'Shahpura', value: 'Rajasthan' },
  { label: 'Sheoganj', value: 'Rajasthan' },
  { label: 'Sikar', value: 'Rajasthan' },
  { label: 'Sirohi', value: 'Rajasthan' },
  { label: 'Sojat', value: 'Rajasthan' },
  { label: 'Sri Madhopur', value: 'Rajasthan' },
  { label: 'Sujangarh', value: 'Rajasthan' },
  { label: 'Sumerpur', value: 'Rajasthan' },
  { label: 'Suratgarh', value: 'Rajasthan' },
  { label: 'Taranagar', value: 'Rajasthan' },
  { label: 'Todabhim', value: 'Rajasthan' },
  { label: 'Todaraisingh', value: 'Rajasthan' },
  { label: 'Tonk', value: 'Rajasthan' },
  { label: 'Udaipur', value: 'Rajasthan' },
  { label: 'Udaipurwati', value: 'Rajasthan' },
  { label: 'Vijainagar', value: 'Rajasthan' },
  { label: 'Gangtok', value: 'Sikkim' },
  { label: 'Calcutta', value: 'West Bengal' },
  { label: 'Arakkonam', value: 'Tamil Nadu' },
  { label: 'Arcot', value: 'Tamil Nadu' },
  { label: 'Aruppukkottai', value: 'Tamil Nadu' },
  { label: 'Bhavani', value: 'Tamil Nadu' },
  { label: 'Chengalpattu', value: 'Tamil Nadu' },
  { label: 'Chennai', value: 'Tamil Nadu' },
  { label: 'Chinna salem', value: 'Tamil nadu' },
  { label: 'Coimbatore', value: 'Tamil Nadu' },
  { label: 'Coonoor', value: 'Tamil Nadu' },
  { label: 'Cuddalore', value: 'Tamil Nadu' },
  { label: 'Dharmapuri', value: 'Tamil Nadu' },
  { label: 'Dindigul', value: 'Tamil Nadu' },
  { label: 'Erode', value: 'Tamil Nadu' },
  { label: 'Gudalur', value: 'Tamil Nadu' },
  { label: 'Gudalur', value: 'Tamil Nadu' },
  { label: 'Gudalur', value: 'Tamil Nadu' },
  { label: 'Kanchipuram', value: 'Tamil Nadu' },
  { label: 'Karaikudi', value: 'Tamil Nadu' },
  { label: 'Karungal', value: 'Tamil Nadu' },
  { label: 'Karur', value: 'Tamil Nadu' },
  { label: 'Kollankodu', value: 'Tamil Nadu' },
  { label: 'Lalgudi', value: 'Tamil Nadu' },
  { label: 'Madurai', value: 'Tamil Nadu' },
  { label: 'Nagapattinam', value: 'Tamil Nadu' },
  { label: 'Nagercoil', value: 'Tamil Nadu' },
  { label: 'Namagiripettai', value: 'Tamil Nadu' },
  { label: 'Namakkal', value: 'Tamil Nadu' },
  { label: 'Nandivaram-Guduvancheri', value: 'Tamil Nadu' },
  { label: 'Nanjikottai', value: 'Tamil Nadu' },
  { label: 'Natham', value: 'Tamil Nadu' },
  { label: 'Nellikuppam', value: 'Tamil Nadu' },
  { label: 'Neyveli', value: 'Tamil Nadu' },
  { label: 'O Valley', value: 'Tamil Nadu' },
  { label: 'Oddanchatram', value: 'Tamil Nadu' },
  { label: 'P.N.Patti', value: 'Tamil Nadu' },
  { label: 'Pacode', value: 'Tamil Nadu' },
  { label: 'Padmanabhapuram', value: 'Tamil Nadu' },
  { label: 'Palani', value: 'Tamil Nadu' },
  { label: 'Palladam', value: 'Tamil Nadu' },
  { label: 'Pallapatti', value: 'Tamil Nadu' },
  { label: 'Pallikonda', value: 'Tamil Nadu' },
  { label: 'Panagudi', value: 'Tamil Nadu' },
  { label: 'Panruti', value: 'Tamil Nadu' },
  { label: 'Paramakudi', value: 'Tamil Nadu' },
  { label: 'Parangipettai', value: 'Tamil Nadu' },
  { label: 'Pattukkottai', value: 'Tamil Nadu' },
  { label: 'Perambalur', value: 'Tamil Nadu' },
  { label: 'Peravurani', value: 'Tamil Nadu' },
  { label: 'Periyakulam', value: 'Tamil Nadu' },
  { label: 'Periyasemur', value: 'Tamil Nadu' },
  { label: 'Pernampattu', value: 'Tamil Nadu' },
  { label: 'Pollachi', value: 'Tamil Nadu' },
  { label: 'Polur', value: 'Tamil Nadu' },
  { label: 'Ponneri', value: 'Tamil Nadu' },
  { label: 'Pudukkottai', value: 'Tamil Nadu' },
  { label: 'Pudupattinam', value: 'Tamil Nadu' },
  { label: 'Puliyankudi', value: 'Tamil Nadu' },
  { label: 'Punjaipugalur', value: 'Tamil Nadu' },
  { label: 'Rajapalayam', value: 'Tamil Nadu' },
  { label: 'Ramanathapuram', value: 'Tamil Nadu' },
  { label: 'Rameshwaram', value: 'Tamil Nadu' },
  { label: 'Rasipuram', value: 'Tamil Nadu' },
  { label: 'Salem', value: 'Tamil Nadu' },
  { label: 'Sankarankoil', value: 'Tamil Nadu' },
  { label: 'Sankari', value: 'Tamil Nadu' },
  { label: 'Sathyamangalam', value: 'Tamil Nadu' },
  { label: 'Sattur', value: 'Tamil Nadu' },
  { label: 'Shenkottai', value: 'Tamil Nadu' },
  { label: 'Sholavandan', value: 'Tamil Nadu' },
  { label: 'Sholingur', value: 'Tamil Nadu' },
  { label: 'Sirkali', value: 'Tamil Nadu' },
  { label: 'Sivaganga', value: 'Tamil Nadu' },
  { label: 'Sivagiri', value: 'Tamil Nadu' },
  { label: 'Sivakasi', value: 'Tamil Nadu' },
  { label: 'Srivilliputhur', value: 'Tamil Nadu' },
  { label: 'Surandai', value: 'Tamil Nadu' },
  { label: 'Suriyampalayam', value: 'Tamil Nadu' },
  { label: 'Tenkasi', value: 'Tamil Nadu' },
  { label: 'Thammampatti', value: 'Tamil Nadu' },
  { label: 'Thanjavur', value: 'Tamil Nadu' },
  { label: 'Tharamangalam', value: 'Tamil Nadu' },
  { label: 'Tharangambadi', value: 'Tamil Nadu' },
  { label: 'Theni Allinagaram', value: 'Tamil Nadu' },
  { label: 'Thirumangalam', value: 'Tamil Nadu' },
  { label: 'Thirunindravur', value: 'Tamil Nadu' },
  { label: 'Thiruparappu', value: 'Tamil Nadu' },
  { label: 'Thirupuvanam', value: 'Tamil Nadu' },
  { label: 'Thiruthuraipoondi', value: 'Tamil Nadu' },
  { label: 'Thiruvallur', value: 'Tamil Nadu' },
  { label: 'Thiruvarur', value: 'Tamil Nadu' },
  { label: 'Thoothukudi', value: 'Tamil Nadu' },
  { label: 'Thuraiyur', value: 'Tamil Nadu' },
  { label: 'Tindivanam', value: 'Tamil Nadu' },
  { label: 'Tiruchendur', value: 'Tamil Nadu' },
  { label: 'Tiruchengode', value: 'Tamil Nadu' },
  { label: 'Tiruchirappalli', value: 'Tamil Nadu' },
  { label: 'Tirukalukundram', value: 'Tamil Nadu' },
  { label: 'Tirukkoyilur', value: 'Tamil Nadu' },
  { label: 'Tirunelveli', value: 'Tamil Nadu' },
  { label: 'Tirupathur', value: 'Tamil Nadu' },
  { label: 'Tirupathur', value: 'Tamil Nadu' },
  { label: 'Tiruppur', value: 'Tamil Nadu' },
  { label: 'Tiruttani', value: 'Tamil Nadu' },
  { label: 'Tiruvannamalai', value: 'Tamil Nadu' },
  { label: 'Tiruvethipuram', value: 'Tamil Nadu' },
  { label: 'Tittakudi', value: 'Tamil Nadu' },
  { label: 'Udhagamandalam', value: 'Tamil Nadu' },
  { label: 'Udumalaipettai', value: 'Tamil Nadu' },
  { label: 'Unnamalaikadai', value: 'Tamil Nadu' },
  { label: 'Usilampatti', value: 'Tamil Nadu' },
  { label: 'Uthamapalayam', value: 'Tamil Nadu' },
  { label: 'Uthiramerur', value: 'Tamil Nadu' },
  { label: 'Vadakkuvalliyur', value: 'Tamil Nadu' },
  { label: 'Vadalur', value: 'Tamil Nadu' },
  { label: 'Vadipatti', value: 'Tamil Nadu' },
  { label: 'Valparai', value: 'Tamil Nadu' },
  { label: 'Vandavasi', value: 'Tamil Nadu' },
  { label: 'Vaniyambadi', value: 'Tamil Nadu' },
  { label: 'Vedaranyam', value: 'Tamil Nadu' },
  { label: 'Vellakoil', value: 'Tamil Nadu' },
  { label: 'Vellore', value: 'Tamil Nadu' },
  { label: 'Vikramasingapuram', value: 'Tamil Nadu' },
  { label: 'Viluppuram', value: 'Tamil Nadu' },
  { label: 'Virudhachalam', value: 'Tamil Nadu' },
  { label: 'Virudhunagar', value: 'Tamil Nadu' },
  { label: 'Viswanatham', value: 'Tamil Nadu' },
  { label: 'Agartala', value: 'Tripura' },
  { label: 'Badharghat', value: 'Tripura' },
  { label: 'Dharmanagar', value: 'Tripura' },
  { label: 'Indranagar', value: 'Tripura' },
  { label: 'Jogendranagar', value: 'Tripura' },
  { label: 'Kailasahar', value: 'Tripura' },
  { label: 'Khowai', value: 'Tripura' },
  { label: 'Pratapgarh', value: 'Tripura' },
  { label: 'Udaipur', value: 'Tripura' },
  { label: 'Achhnera', value: 'Uttar Pradesh' },
  { label: 'Adari', value: 'Uttar Pradesh' },
  { label: 'Agra', value: 'Uttar Pradesh' },
  { label: 'Aligarh', value: 'Uttar Pradesh' },
  { label: 'Allahabad', value: 'Uttar Pradesh' },
  { label: 'Amroha', value: 'Uttar Pradesh' },
  { label: 'Azamgarh', value: 'Uttar Pradesh' },
  { label: 'Bahraich', value: 'Uttar Pradesh' },
  { label: 'Ballia', value: 'Uttar Pradesh' },
  { label: 'Balrampur', value: 'Uttar Pradesh' },
  { label: 'Banda', value: 'Uttar Pradesh' },
  { label: 'Bareilly', value: 'Uttar Pradesh' },
  { label: 'Chandausi', value: 'Uttar Pradesh' },
  { label: 'Dadri', value: 'Uttar Pradesh' },
  { label: 'Deoria', value: 'Uttar Pradesh' },
  { label: 'Etawah', value: 'Uttar Pradesh' },
  { label: 'Fatehabad', value: 'Uttar Pradesh' },
  { label: 'Fatehpur', value: 'Uttar Pradesh' },
  { label: 'Fatehpur', value: 'Uttar Pradesh' },
  { label: 'Greater Noida', value: 'Uttar Pradesh' },
  { label: 'Hamirpur', value: 'Uttar Pradesh' },
  { label: 'Hardoi', value: 'Uttar Pradesh' },
  { label: 'Jajmau', value: 'Uttar Pradesh' },
  { label: 'Jaunpur', value: 'Uttar Pradesh' },
  { label: 'Jhansi', value: 'Uttar Pradesh' },
  { label: 'Kalpi', value: 'Uttar Pradesh' },
  { label: 'Kanpur', value: 'Uttar Pradesh' },
  { label: 'Kota', value: 'Uttar Pradesh' },
  { label: 'Laharpur', value: 'Uttar Pradesh' },
  { label: 'Lakhimpur', value: 'Uttar Pradesh' },
  { label: 'Lal Gopalganj Nindaura', value: 'Uttar Pradesh' },
  { label: 'Lalganj', value: 'Uttar Pradesh' },
  { label: 'Lalitpur', value: 'Uttar Pradesh' },
  { label: 'Lar', value: 'Uttar Pradesh' },
  { label: 'Loni', value: 'Uttar Pradesh' },
  { label: 'Lucknow', value: 'Uttar Pradesh' },
  { label: 'Mathura', value: 'Uttar Pradesh' },
  { label: 'Meerut', value: 'Uttar Pradesh' },
  { label: 'Modinagar', value: 'Uttar Pradesh' },
  { label: 'Muradnagar', value: 'Uttar Pradesh' },
  { label: 'Nagina', value: 'Uttar Pradesh' },
  { label: 'Najibabad', value: 'Uttar Pradesh' },
  { label: 'Nakur', value: 'Uttar Pradesh' },
  { label: 'Nanpara', value: 'Uttar Pradesh' },
  { label: 'Naraura', value: 'Uttar Pradesh' },
  { label: 'Naugawan Sadat', value: 'Uttar Pradesh' },
  { label: 'Nautanwa', value: 'Uttar Pradesh' },
  { label: 'Nawabganj', value: 'Uttar Pradesh' },
  { label: 'Nehtaur', value: 'Uttar Pradesh' },
  { label: 'NOIDA', value: 'Uttar Pradesh' },
  { label: 'Noorpur', value: 'Uttar Pradesh' },
  { label: 'Obra', value: 'Uttar Pradesh' },
  { label: 'Orai', value: 'Uttar Pradesh' },
  { label: 'Padrauna', value: 'Uttar Pradesh' },
  { label: 'Palia Kalan', value: 'Uttar Pradesh' },
  { label: 'Parasi', value: 'Uttar Pradesh' },
  { label: 'Phulpur', value: 'Uttar Pradesh' },
  { label: 'Pihani', value: 'Uttar Pradesh' },
  { label: 'Pilibhit', value: 'Uttar Pradesh' },
  { label: 'Pilkhuwa', value: 'Uttar Pradesh' },
  { label: 'Powayan', value: 'Uttar Pradesh' },
  { label: 'Pukhrayan', value: 'Uttar Pradesh' },
  { label: 'Puranpur', value: 'Uttar Pradesh' },
  { label: 'Purquazi', value: 'Uttar Pradesh' },
  { label: 'Purwa', value: 'Uttar Pradesh' },
  { label: 'Rae Bareli', value: 'Uttar Pradesh' },
  { label: 'Rampur', value: 'Uttar Pradesh' },
  { label: 'Rampur Maniharan', value: 'Uttar Pradesh' },
  { label: 'Rasra', value: 'Uttar Pradesh' },
  { label: 'Rath', value: 'Uttar Pradesh' },
  { label: 'Renukoot', value: 'Uttar Pradesh' },
  { label: 'Reoti', value: 'Uttar Pradesh' },
  { label: 'Robertsganj', value: 'Uttar Pradesh' },
  { label: 'Rudauli', value: 'Uttar Pradesh' },
  { label: 'Rudrapur', value: 'Uttar Pradesh' },
  { label: 'Sadabad', value: 'Uttar Pradesh' },
  { label: 'Safipur', value: 'Uttar Pradesh' },
  { label: 'Saharanpur', value: 'Uttar Pradesh' },
  { label: 'Sahaspur', value: 'Uttar Pradesh' },
  { label: 'Sahaswan', value: 'Uttar Pradesh' },
  { label: 'Sahawar', value: 'Uttar Pradesh' },
  { label: 'Sahjanwa', value: 'Uttar Pradesh' },
  { label: 'Saidpur', value: ' Ghazipur' },
  { label: 'Sambhal', value: 'Uttar Pradesh' },
  { label: 'Samdhan', value: 'Uttar Pradesh' },
  { label: 'Samthar', value: 'Uttar Pradesh' },
  { label: 'Sandi', value: 'Uttar Pradesh' },
  { label: 'Sandila', value: 'Uttar Pradesh' },
  { label: 'Sardhana', value: 'Uttar Pradesh' },
  { label: 'Seohara', value: 'Uttar Pradesh' },
  { label: 'Shahabad', value: ' Hardoi' },
  { label: 'Shahabad', value: ' Rampur' },
  { label: 'Shahganj', value: 'Uttar Pradesh' },
  { label: 'Shahjahanpur', value: 'Uttar Pradesh' },
  { label: 'Shamli', value: 'Uttar Pradesh' },
  { label: 'Shamsabad', value: ' Agra' },
  { label: 'Shamsabad', value: ' Farrukhabad' },
  { label: 'Sherkot', value: 'Uttar Pradesh' },
  { label: 'Shikarpur', value: ' Bulandshahr' },
  { label: 'Shikohabad', value: 'Uttar Pradesh' },
  { label: 'Shishgarh', value: 'Uttar Pradesh' },
  { label: 'Siana', value: 'Uttar Pradesh' },
  { label: 'Sikanderpur', value: 'Uttar Pradesh' },
  { label: 'Sikandra Rao', value: 'Uttar Pradesh' },
  { label: 'Sikandrabad', value: 'Uttar Pradesh' },
  { label: 'Sirsaganj', value: 'Uttar Pradesh' },
  { label: 'Sirsi', value: 'Uttar Pradesh' },
  { label: 'Sitapur', value: 'Uttar Pradesh' },
  { label: 'Soron', value: 'Uttar Pradesh' },
  { label: 'Suar', value: 'Uttar Pradesh' },
  { label: 'Sultanpur', value: 'Uttar Pradesh' },
  { label: 'Sumerpur', value: 'Uttar Pradesh' },
  { label: 'Tanda', value: 'Uttar Pradesh' },
  { label: 'Tanda', value: 'Uttar Pradesh' },
  { label: 'Tetri Bazar', value: 'Uttar Pradesh' },
  { label: 'Thakurdwara', value: 'Uttar Pradesh' },
  { label: 'Thana Bhawan', value: 'Uttar Pradesh' },
  { label: 'Tilhar', value: 'Uttar Pradesh' },
  { label: 'Tirwaganj', value: 'Uttar Pradesh' },
  { label: 'Tulsipur', value: 'Uttar Pradesh' },
  { label: 'Tundla', value: 'Uttar Pradesh' },
  { label: 'Unnao', value: 'Uttar Pradesh' },
  { label: 'Utraula', value: 'Uttar Pradesh' },
  { label: 'Varanasi', value: 'Uttar Pradesh' },
  { label: 'Vrindavan', value: 'Uttar Pradesh' },
  { label: 'Warhapur', value: 'Uttar Pradesh' },
  { label: 'Zaidpur', value: 'Uttar Pradesh' },
  { label: 'Zamania', value: 'Uttar Pradesh' },
  { label: 'Almora', value: 'Uttarakhand' },
  { label: 'Bazpur', value: 'Uttarakhand' },
  { label: 'Chamba', value: 'Uttarakhand' },
  { label: 'Dehradun', value: 'Uttarakhand' },
  { label: 'Haldwani', value: 'Uttarakhand' },
  { label: 'Haridwar', value: 'Uttarakhand' },
  { label: 'Jaspur', value: 'Uttarakhand' },
  { label: 'Kashipur', value: 'Uttarakhand' },
  { label: 'kichha', value: 'Uttarakhand' },
  { label: 'Kotdwara', value: 'Uttarakhand' },
  { label: 'Manglaur', value: 'Uttarakhand' },
  { label: 'Mussoorie', value: 'Uttarakhand' },
  { label: 'Nagla', value: 'Uttarakhand' },
  { label: 'Nainital', value: 'Uttarakhand' },
  { label: 'Pauri', value: 'Uttarakhand' },
  { label: 'Pithoragarh', value: 'Uttarakhand' },
  { label: 'Ramnagar', value: 'Uttarakhand' },
  { label: 'Rishikesh', value: 'Uttarakhand' },
  { label: 'Roorkee', value: 'Uttarakhand' },
  { label: 'Rudrapur', value: 'Uttarakhand' },
  { label: 'Sitarganj', value: 'Uttarakhand' },
  { label: 'Tehri', value: 'Uttarakhand' },
  { label: 'Muzaffarnagar', value: 'Uttar Pradesh' },
  { label: 'Adra', value: ' Purulia' },
  { label: 'Alipurduar', value: 'West Bengal' },
  { label: 'Arambagh', value: 'West Bengal' },
  { label: 'Asansol', value: 'West Bengal' },
  { label: 'Baharampur', value: 'West Bengal' },
  { label: 'Bally', value: 'West Bengal' },
  { label: 'Balurghat', value: 'West Bengal' },
  { label: 'Bankura', value: 'West Bengal' },
  { label: 'Barakar', value: 'West Bengal' },
  { label: 'Barasat', value: 'West Bengal' },
  { label: 'Bardhaman', value: 'West Bengal' },
  { label: 'Bidhan Nagar', value: 'West Bengal' },
  { label: 'Chinsura', value: 'West Bengal' },
  { label: 'Contai', value: 'West Bengal' },
  { label: 'Cooch Behar', value: 'West Bengal' },
  { label: 'Darjeeling', value: 'West Bengal' },
  { label: 'Durgapur', value: 'West Bengal' },
  { label: 'Haldia', value: 'West Bengal' },
  { label: 'Howrah', value: 'West Bengal' },
  { label: 'Islampur', value: 'West Bengal' },
  { label: 'Jhargram', value: 'West Bengal' },
  { label: 'Kharagpur', value: 'West Bengal' },
  { label: 'Kolkata', value: 'West Bengal' },
  { label: 'Mainaguri', value: 'West Bengal' },
  { label: 'Mal', value: 'West Bengal' },
  { label: 'Mathabhanga', value: 'West Bengal' },
  { label: 'Medinipur', value: 'West Bengal' },
  { label: 'Memari', value: 'West Bengal' },
  { label: 'Monoharpur', value: 'West Bengal' },
  { label: 'Murshidabad', value: 'West Bengal' },
  { label: 'Nabadwip', value: 'West Bengal' },
  { label: 'Naihati', value: 'West Bengal' },
  { label: 'Panchla', value: 'West Bengal' },
  { label: 'Pandua', value: 'West Bengal' },
  { label: 'Paschim Punropara', value: 'West Bengal' },
  { label: 'Purulia', value: 'West Bengal' },
  { label: 'Raghunathpur', value: 'West Bengal' },
  { label: 'Raiganj', value: 'West Bengal' },
  { label: 'Rampurhat', value: 'West Bengal' },
  { label: 'Ranaghat', value: 'West Bengal' },
  { label: 'Sainthia', value: 'West Bengal' },
  { label: 'Santipur', value: 'West Bengal' },
  { label: 'Siliguri', value: 'West Bengal' },
  { label: 'Sonamukhi', value: 'West Bengal' },
  { label: 'Srirampore', value: 'West Bengal' },
  { label: 'Suri', value: 'West Bengal' },
  { label: 'Taki', value: 'West Bengal' },
  { label: 'Tamluk', value: 'West Bengal' },
  { label: 'Tarakeswar', value: 'West Bengal' },
  { label: 'Chikmagalur', value: 'Karnataka' },
  { label: 'Davanagere', value: 'Karnataka' },
  { label: 'Dharwad', value: 'Karnataka' },
  { label: 'Gadag', value: 'Karnataka' },
  { label: 'Chennai', value: 'Tamil Nadu' },
  { label: 'Coimbatore', value: 'Tamil Nadu' },
];
