const stateCodes = {
  andamanandnicobarislands: '35',
  andhrapradesh: '37',
  arunachalpradesh: '12',
  assam: '18',
  bihar: '10',
  chandigarh: '04',
  chhattisgarh: '22',
  dadraandnagarhaveli: '26',
  damananddiu: '26',
  delhi: '07',
  goa: '30',
  gujarat: '24',
  haryana: '06',
  himachalpradesh: '02',
  jammuandkashmir: '01',
  jharkhand: '20',
  karnataka: '29',
  kerala: '32',
  ladakh: '38',
  lakshadweep: '31',
  madhyapradesh: '23',
  maharashtra: '27',
  manipur: '14',
  meghalaya: '17',
  mizoram: '15',
  nagaland: '13',
  odisha: '21',
  puducherry: '34',
  punjab: '03',
  rajasthan: '08',
  sikkim: '11',
  tamilnadu: '33',
  telangana: '36',
  tripura: '16',
  uttarpradesh: '09',
  uttarakhand: '05',
  westbengal: '19',
};

export default stateCodes;
