export const statusConstants = {
  INDENT_CREATED: 'INDENT_CREATED',
  APPROVED: 'APPROVED',
  VENDOR_ASSIGNED: 'VENDOR_ASSIGNED',
  ORDER_CONFIRMED: 'ORDER_CONFIRMED',
  PO_CREATED: 'PO_CREATED',
  INDENT_CLOSED: 'INDENT_CLOSED',
  DELIVERED: 'DELIVERED',
  INWARD: 'INWARD',
  BILL: 'BILL',
  PAYMENT: 'PAYMENT',
  PO_CLOSED: 'PO_CLOSED',
};
