export const purchaseReportsArray = [
  {
    heading: 'Purchase Reports',
    reports: [
      {
        title: 'Purchase Over Time',
        onCardParam: 'PurchaseOverTime',
        description: 'Track total purchases over a selected period',
      },
      {
        title: 'Purchase by Vendors Summary',
        onCardParam: 'PurchaseByVendorSummary',
        description: 'Overview of total purchases from vendors',
      },
      {
        title: 'Purchase by Item-wise',
        onCardParam: 'PurchaseByItemWise',
        description: 'Provides a breakdown of purchases by individual items',
      },
      {
        title: 'Purchase by Category',
        onCardParam: 'PurchaseByCategory',
        description: 'Breakdown of total purchases by product categories',
      },
      {
        title: 'Purchase by Brand',
        onCardParam: 'PurchaseByBrand',
        description: 'Breakdown of total purchases by brand name',
      },
      {
        title: 'Purchase Indent Summary',
        onCardParam: 'PurchaseIndentSummary',
        description: 'Overview of all purchase indents raised',
      },
      {
        title: 'Purchase Indent Report',
        onCardParam: 'PurchaseIndentReport',
        description: 'Detailed view of PIs, including created, approved, etc',
      },
      {
        title: 'Purchase Orders Summary',
        onCardParam: 'PurchaseOrdersSummary',
        description: 'Overview of all purchase orders',
      },
      {
        title: 'Purchase Order Report',
        onCardParam: 'PurchaseOrderReport',
        description: 'Detailed view of POs, including approved, rejected, etc',
      },
      {
        title: 'Purchase Returns Summary',
        onCardParam: 'PurchaseReturnsSummary',
        description: 'Overview of returned purchases, showing total returns, reasons etc',
      },
      {
        title: 'Purchase Return Bill-wise Report',
        onCardParam: 'PurchaseReturnBillWiseReport',
        description: 'Tracks purchase returns on a bill-by-bill basis',
      },
      {
        title: 'Purchase Return Item-wise Report',
        onCardParam: 'PurchaseReturnItemWiseReport',
        description: 'Detailed report of returned items',
      },
      {
        title: 'Purchase Return Vendor-wise Report',
        onCardParam: 'PurchaseReturnVendorWiseReport',
        description: 'Tracks items returned made to each vendor',
      },
      {
        title: 'GRN Summary',
        onCardParam: 'GrnSummary',
        description: 'Overview of all express Goods Received Notes (GRNs)',
      },
      {
        title: 'GRN Margin Vendor-wise Report',
        onCardParam: 'GrnMarginVendorWiseReport',
        description: 'Detailed view of express GRNs by vendor',
      },
      {
        title: 'GRN Margin Item-wise Report',
        onCardParam: 'GrnMarginItemWiseReport',
        description: 'Tracks express GRNs item-wise, showing quantities etc',
      },
      {
        title: 'GRN PO-wise Report',
        onCardParam: 'GrnPoWiseReport',
        description: 'Identifies express GRNs to specific purchase orders',
      },
      { title: 'GRN Pending Report', onCardParam: 'GrnPendingReport', description: '' },
      { title: 'Quantity Rejection Report', onCardParam: 'QuantityRejectionReport', description: '' },
      {
        title: 'Top Purchase Items',
        onCardParam: 'TopPurchaseItems',
        description: 'Identifies highest-purchased items based on quantity or value',
      },
      { title: 'Purchase Forecasting Report', onCardParam: 'PurchaseForecastingReport', description: '' },
      { title: 'Vendor GST Details', onCardParam: 'VendorGstDetails', description: '' },
      { title: 'Non GST Vendor Details', onCardParam: 'NonGstVendorDetails', description: '' },
      { title: 'Vendor Transaction Summary', onCardParam: 'VendorTransactionSummary', description: '' },
      { title: 'Vendor Transaction Detail Report', onCardParam: 'VendorTransactionDetailReport', description: '' },
      { title: 'Stock Transfer Report', onCardParam: 'StockTransferReport', description: '' },
      { title: 'Stock Transfer Pending Report', onCardParam: 'StockTransferPendingReport', description: '' },
      { title: 'Auditor Purchase Report', onCardParam: 'AuditorPurchaseReport', description: '' },
      {
        title: 'Purchase With Sales Analysis Report',
        onCardParam: 'PurchaseWithSalesAnalysisReport',
        description: '',
      },
      {
        title: 'Vendor payment Summary',
        onCardParam: 'VendorPaymentSummary',
        description: '',
      },
      {
        title: 'Unpaid Vendor Report',
        onCardParam: 'UnpaidVendorReport',
        description: '',
      },
      {
        title: 'Vendor wise Purchase Report',
        onCardParam: 'VendorWisePurchaseReport',
        description: '',
      },
      {
        title: 'Vendor wise GRN Report',
        onCardParam: 'VendorWiseGrnReport',
        description: '',
      },
      {
        title: 'Category wise Purchase Report',
        onCardParam: 'CategoryWisePurchaseReport',
        description: '',
      },
      {
        title: 'Vendor Items list Report',
        onCardParam: 'VendorItemsList',
        description: '',
      },
    ],
  },
];
export const InventoryReportArray = [
  { title: 'Inventory over time', key: 'InventoryOverTime' },
  { title: 'Inventory based on analysis', key: 'InventoryBasedOnAnalysis' },
  { title: 'Inventory by day', key: 'InventoryByDay' },
  { title: 'Invalid Price Conditions', key: 'InvalidPriceConditions' },
  { title: 'Slow moving inventory', key: 'SlowMovingInventory' },
  { title: 'Wastage Report', key: 'WastageReport' },
  { title: 'Expired Products', key: 'ExpiredProducts' },

  { title: 'Products Expiring Today', key: 'ProductsExpiringToday' },
  { title: 'Expired Products in the Last 30 Days', key: 'ExpiredProductsInTheLast 30Days' },
  { title: 'Products Expiring in the Next 7 Days', key: 'ProductsExpiringInTheNext 7Days' },
  { title: 'Products Expiring in the Next 14 Days', key: 'ProductsExpiringInTheNext 14Days' },
  { title: 'Expired Product Adjustments Report', key: 'ExpiredProductAdjustmentsReport' },
  { title: 'Manual Inventory Adjustments Report', key: 'ManualInventoryAdjustmentsReport' },
  { title: 'Wastage Adjustments Report', key: 'WastageAdjustmentsReport' },
  { title: 'Stock Aging Report (Last 3 Months)', key: 'StockAgingReport (Last 3 Months)' },
  { title: 'Inactive Inventory Products Report', key: 'InactiveInventoryProductsReport' },
  { title: 'Active Inventory Products Report', key: 'ActiveInventoryProductsReport' },
  { title: 'Negative Inventory Stock Report', key: 'NegativeInventoryStockReport' },
  { title: 'Inventory Stock Report', key: 'InventoryStockReport' },
  { title: 'Day Wise Item Report', key: 'DayWiseItemReport' },
  { title: 'Inventory Daily Oversold Report', key: 'InventoryDailyOversoldReport' },
  { title: 'Inventory Adjustment Stock Count', key: 'InventoryAdjustmentStockCount' },

  { title: 'Daily Stock Report', key: 'Daily-Stock-Report', available: false },
  { title: 'Inventory by product vendor', key: 'InventoryByProductVendor', available: false },
  { title: 'Average inventory sold by day', key: 'AverageInventorySoldByDay', available: false },
  { title: 'Stock turnover ratio', key: 'StockTurnoverRatio', available: false },
  { title: 'Inventory cost', key: 'InventoryCost', available: false },
  { title: 'Slow Moving Category Wise Stock Summary', key: 'SlowMovingCategoryWiseStockSummary', available: false },
  { title: 'Fast Moving Item Wise Stock Summary', key: 'FastMovingItemWiseStockSummary', available: false },
  { title: 'Fast Moving-Category Wise Stock Summary', key: 'FastMovingCategoryWiseStockSummary', available: false },
  { title: 'Slow Moving Supplier wise Report', key: 'SlowMovingSupplierWiseReport', available: false },
  { title: 'Expiry Stock-As on', key: 'ExpiryStockAsOn', available: false },
  { title: 'Expiry Stock', key: 'ExpiryStock', available: false },
  { title: 'Non Moving- Age Wise', key: 'NonMovingAgeWise', available: false },
  { title: 'Non Moving Stock Summary', key: 'NonMovingStockSummary', available: false },
  { title: 'Repack-Item Wise Detailed', key: 'RepackItemWiseDetailed', available: false },
  { title: 'Reorder Report', key: 'ReorderReport', available: false },
  { title: 'Category Wise Summary', key: 'CategoryWiseSummary', available: false },
  { title: 'Supplier wise item summary', key: 'SupplierWiseItemSummary', available: false },
  { title: 'Location wise item summary', key: 'LocationWiseItemSummary', available: false },
  { title: 'Stock Category wise Margin', key: 'StockCategoryWiseMargin', available: false },
];

export const salesReportArray = [
  { title: 'Sales over time', onCardParam: 'Sales Over Time', available: true },
  { title: 'Sales by Product', onCardParam: 'Sales by Product', available: true },
  { title: 'Profit and loss report', onCardParam: 'Profit and loss report', available: true },
  { title: 'Sales by Payment method', onCardParam: 'Sales by Payment method', available: true },
  { title: 'Day wise Business report', onCardParam: 'Day wise Business report', available: true },
  { title: 'HSN wise sales report', onCardParam: 'HSN wise sales report', available: true },
  { title: 'Daily profit report', onCardParam: 'Daily profit report ', available: true },
  { title: 'Item wise sales report', onCardParam: 'Item wise sales report', available: true },
  { title: 'Sales GST registration report', onCardParam: 'Sales GST registration report', available: true },

  { title: 'Session report', onCardParam: 'Session', available: true, pos: true },
  { title: 'End of day report', onCardParam: 'End of Day', available: true, pos: true },
  { title: 'Sales by product vendor', onCardParam: 'Sales by product vendor' },
  { title: 'Sales by Point of Sale', onCardParam: 'Sales by Point of Sale' },
  { title: 'Sales by discount', onCardParam: 'Sales by discount' },
  { title: 'Sales by location', onCardParam: 'Sales by location' },
  { title: 'Sales by channel', onCardParam: 'Sales by channel' },
  { title: 'Sales by brand', onCardParam: 'Sales by brand' },
  { title: 'Sales by customer', onCardParam: 'Sales by customer' },
  { title: 'Average order value over time', onCardParam: 'Average order value over time' },
  { title: 'Sales Return Reports', onCardParam: 'Sales Return Reports' },
  { title: 'Sales Report', onCardParam: 'Sales Report' },
  { title: 'Sales Cancelled Bill Report', onCardParam: 'Sales Cancelled Bill Report' },
  { title: 'Sales Order report', onCardParam: 'Sales Order report' },
  { title: 'POS UPI sales', onCardParam: 'POS UPI sales' },
  { title: 'POS Card sales', onCardParam: 'POS Card sales' },
  { title: 'POS offline sales', onCardParam: 'POS offline sales' },
  { title: 'POS adjusted orders', onCardParam: 'POS adjusted orders' },
  { title: 'POS credit notes', onCardParam: 'POS credit notes' },
];

export const gstReportArray = [
  {
    heading: 'Purchase',
    reports: [
      { title: 'GST Purchases Summary', onCardParam: 'GstPurchasesSummary' },
      { title: 'Purchase GST Report Po wise', onCardParam: 'PurchaseGstReportPoWise' },
      { title: 'Purchase GST Report Bill wise', onCardParam: 'PurchaseGstReportBillWise' },
      { title: 'Purchase GST report Item Wise', onCardParam: 'PurchaseGstReportItemWise' },
      { title: 'Purchase GST report Vendor wise', onCardParam: 'PurchaseGstReportVendorWise' },
      { title: 'Purchase GST report by vendor', onCardParam: 'purchaseGstReportByVendor' },
      { title: 'Purchase with Return GST Report', onCardParam: 'PurchaseWithReturnGstReport' },
      { title: 'Purchase Return GST Report Invoice-wise', onCardParam: 'PurchaseReturnGstReportInvoiceWise' },
      { title: 'Purchase Return GST Report Item wise', onCardParam: 'PurchaseReturnGstReportItemWise' },
      { title: 'Purchase Return GST Report Vendor wise', onCardParam: 'PurchaseReturnGstReportVendorWise' },
      { title: `Express GRN GST Summary`, onCardParam: `ExpressGrnGstSummary` },
      { title: 'Express GRN GST Report', onCardParam: 'ExpressGrnGstReport' },
    ],
  },
  {
    heading: 'Sales',
    reports: [
      { title: 'Gst sales report', onCardParam: 'GstSalesReport' },
      { title: 'GST Consolidate report', onCardParam: 'GstConsolidateReport' },
    ],
  },
];

export const billReportArray = [
  { title: 'Bills Master Report', onCardParam: 'BillsMasterReport' },
  { title: 'Invoice-wise Bills Report', onCardParam: 'InvoiceWiseBillsReport' },
  { title: 'Vendor Wise Bills Summary', onCardParam: 'VendorWiseBillsSummary' },
  { title: 'Bills by Vendor Report', onCardParam: 'BillsByVendorReport' },
  { title: 'Po-wise Bills Report', onCardParam: 'PoWiseBillsReport' },
  { title: 'Bills Pending Payment Report', onCardParam: 'BillsPendingPaymentReport' },
  { title: 'Payments Summary', onCardParam: 'PaymentsSummary' },
  { title: 'Payment by Vendor wise Report', onCardParam: 'paymentByVendorWiseReport' },
  { title: ' Bill Wise Payment Report', onCardParam: 'BillWisePaymentReport' },
];

export const marketingReportArray = [{ title: 'Coupon Report', path: '/reports/marketing/Coupon-Report' }];
export const OperatorReportArray = [
  { title: 'Intrusion Reports', path: '/reports/operator-effectiveness' },
  { title: 'Cart Delete reports', path: '/reports/operator-effectiveness' },
];
